### ISSUE TITLE
"Install Extensions" comes up empty

### ISSUE THREAD

**Issue by hruvulum** [VSCodium/vscodium#107]
When I run the "Install Extensions" command in vscode, a list of over 10,000 extensions appear in the side bar. When I run the same command in vscodium, it says, "no extensions found". This is on Windows 10.

**Comment by stripedpajamas** [comment]
That is sad @hruvulum 😢 Can you reply back with this info?

- arch (32-bit or 64-bit)
- version of VSCodium
- system setup or user setup used to install

**Comment by hruvulum** [comment]
64-bit, version 1.33.0, user setup.

Since writing my bug report, I found some other way to get uninstalled extensions to be listed in the side bar in the extensions view, so the motivation for my writing this bug report is gone, but I stand ready to help in any way I can if you still want to try to fix it.

**Comment by stripedpajamas** [comment]
Can you share your workaround? The extensions marketplace should be set by the `product.json` file during build time, which is used across Linux/Mac/Windows builds.

**Comment by hruvulum** [comment]
When I run the command "Show Popular Extensions" on the menu under the icon in the top right corner of the extensions view, the extensions view is populated by a very long list of extensions sorted by how many times they have been installed.

**Comment by stripedpajamas** [comment]
Oh I see what's going on now. Yes I also experience the original issue of there being no "Recommended Extensions". Searching the extensions or choosing the Sort By Name | Rating | Install Count works. I'm not sure why there aren't any recommended extensions, but I think extension recommendations come from hitting a Microsoft API so it may be related to us disabling telemetry. Since extension listing and installation work in general I'll close this one out.

**Comment by hruvulum** [comment]
You don't want to remove "Extensions: Install Extensions" from the name space to avoid discouraging people kicking VSCodium's tires?

I am very new to VSCodium, and when I set myself the goal of installing an extension, "Extensions: Install Extensions" is the first thing I tried.
