### ISSUE TITLE
ia32 x86 Build not released on 1.67.0

### ISSUE THREAD

**Issue by angelivan-spartan** [VSCodium/vscodium#1077]
**Describe the bug**
The windows x86 build is not present at https://github.com/VSCodium/vscodium/releases/tag/1.67.0

**Please confirm that this problem is VSCodium-specific**
Visual Studio Code have a current build for x86 on version 1.67.0
it looks like was out of the build on commit [fix(1.67): update patches (](https://github.com/VSCodium/vscodium/commit/0932463dfb5672c657cc41db2c2ae07f08cb1fbb)https://github.com/VSCodium/vscodium/pull/1066[)](https://github.com/VSCodium/vscodium/commit/0932463dfb5672c657cc41db2c2ae07f08cb1fbb)

**Please confirm that the issue/resolution isn't already documented**
didn't find the issue, and x86 was available at 1.66.2 of vscodium and previous

**To Reproduce**
1. Go to ['Release 1.67.0'](https://github.com/VSCodium/vscodium/releases/tag/1.67.0)
2. there isn't  VSCodium-win32-ia32-1.67.0.zip  

**Expected behavior**
Have a vscodium build for win 32bit?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win7 x86 to win10 x86
 - Architecture ia32
 - Version 1.67.0

**Additional context**
[fix(1.67): update patches (](https://github.com/VSCodium/vscodium/commit/0932463dfb5672c657cc41db2c2ae07f08cb1fbb)https://github.com/VSCodium/vscodium/pull/1066[)](https://github.com/VSCodium/vscodium/commit/0932463dfb5672c657cc41db2c2ae07f08cb1fbb)

**Comment by al-lac** [comment]
Same issue for `1.67.1`

**Comment by Thilas** [comment]
@daiyam, this issue prevents the chocolatey packages to be updated ([vscodium](https://community.chocolatey.org/packages/vscodium), [vscodium.install](https://community.chocolatey.org/packages/vscodium.install) & [vscodium.portable](https://community.chocolatey.org/packages/vscodium.portable)). Could it be fixed asap please?

Please note that both VSCodiumSetup-ia32 exe file and VSCodium-win32-ia32 zip file are missing since version 1.67.0.

Thanks

**Comment by daiyam** [comment]
I will when I have some time...

**Comment by daiyam** [comment]
The packages have been released via the PR https://github.com/VSCodium/vscodium/pull/1082
