### ISSUE TITLE
"Git History" extension make VSCodium send telemetry out

### ISSUE THREAD

**Issue by lessload** [VSCodium/vscodium#1087]
**Describe the bug**
"Git History" extension make VSCodium send telemetry out

**To Reproduce**
- I have to monitor VSCodium.exe by firewall apps.
- I found VSCodium.exe try to connect to 40.79.170.242 tcp port 443, that is `dc.services.visualstudio.com`
- I try to disable "Git History" extension. and connection was gone. Test it 3 time for confirmation.

**Expected behavior**
VSCodium.exe should not connect to any telemetry server

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Architecture x64
 - Version 1.67.2

**Additional context**
It's may extension problem. but VSCodium should have the way to block it.

**Comment by paulcarroty** [comment]
Full extension id and version please. I can't reproduce it on Linux.

**Comment by daiyam** [comment]
The telemetry is fully backed in the extension (https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/common/telemetry.ts).
It isn't due to VSCodium.

Note sure if there a way to block it from VSCodium... further research need to be done...

I will leave the issue open until I found out if that telemetry can be blocked or not.

**Comment by daiyam** [comment]
That extension is still using the old setting to disable the telemetry (`"telemetry.enableTelemetry": false,`, https://github.com/DonJayamanne/gitHistoryVSCode/blob/75575aa03d03a06a2b901944d65a0f58f4875e02/src/common/telemetry.ts#L20)
