### ISSUE TITLE
VSCodium can't open browser window

### ISSUE THREAD

**Issue by Nasko-5** [VSCodium/vscodium#1089]
Issue Type: <b>Bug</b>

My os is ZorinOS 16.1,
I have firefox 100.0.2 and VSCodium 1.67

When an extention tries to open my browser it'll crash saying there's an input/output error and an extra mozzila crash reporter window.

As for replicating the issue, i don't really know what's causing it..

VS Code version: VSCodium 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-19T00:31:55.273Z)
OS version: Linux x64 5.13.0-41-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T9400  @ 2.53GHz (2 x 2520)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|3.73GB (0.66GB free)|
|Process Argv|--ms-enable-electron-run-as-node --no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|zorin-os-lite|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|zorin-os-lite|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
code-runner|for|0.11.7
vsc-python-indent|Kev|1.15.0
kite|kit|0.147.0
python|ms-|2022.6.2
jupyter|ms-|2022.5.1001290443
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
rust|rus|0.7.8
sonarlint-vscode|Son|3.4.0

</details>

**Comment by moobsen** [comment]
I might be having the same (a similar?) problem on Ubuntu 22.04 LTS. When I try to debug in firefox I get the error:
  "Your Firefox profile cannot be loaded. It may be missing or inaccessible."

I think in my case it is due to sandboxing done by snap.
firefox: 100.0.2-1 (snap)
VS Codium 1.67.2 (snap, classic)

I assume codium tries to create an empty firefox profile, which fails because of sandboxing. As a quick workaround I tried to install firefox with the --classic flag in snap, but snap told me this will be ignored. (Warning: flag --classic ignored for strictly confined snap firefox). And I like my browser sandboxed in any case.

As a work around I currently use chromium to debug, which still is installed in classic mode.

**Comment by moobsen** [comment]
The above work around stopped working for me. 

But using this guide https://github.com/firefox-devtools/vscode-firefox-debug#attach I was able to configure the firefox dev edition and attach the debugger to it. Only that the correct flag under linux is:

`firefox --start-debugger-server`
