### ISSUE TITLE
Rename macOS app to VSCodium.app

### ISSUE THREAD

**Issue by MatiasConTilde** [VSCodium/vscodium#11]
As pointed out in https://github.com/Homebrew/homebrew-cask/pull/51727#discussion_r216155232, the token has to be named the same way as the App file to be included in Homebrew Cask, this means either renaming the app file to VSCodium.app or changing the token to `code-oss`. I personally like the first option more as it includes the name of this project so it isn't that general.

**Comment by stripedpajamas** [comment]
@MatiasConTilde first of all thank you for spearheading the Brew issue. I'm for renaming the app to VSCodium as well, as that is a very small change pre-build and doesn't affect the end product at all (besides aesthetically). Instead of just renaming the macOS app, I think it would be more straightforward to edit the `product.json` file before building. This would affect the name of the resulting app for all platforms. 

My thought would be to leave the data directory name (`.vscode-oss`) untouched, so that the config/extensions used in anyone's built-from-source copy would be shared in a downloaded copy of VSCodium.
