### ISSUE TITLE
Change extensions folder

### ISSUE THREAD

**Issue by ShayBox** [VSCodium/vscodium#114]
The `~/.vscode-oss` folder should be changed to `~/.vscodium` as it conflicts with the existing `Code - OSS` project, which would make it have to be conflicting in every package manager.

**Comment by stripedpajamas** [comment]
This is by design. VSCodium and Code - OSS are ostensibly the same product. If a package manager allows you to install Code - OSS you really don't need VSCodium. VSCodium is an automated build of the vscode sources; Code - OSS is what one gets if one builds them manually. We wanted the two to share configuration and extension data. 

It's important that this project is not seen as a fork because it isn't. These are CI scripts to run the builds already written by Microsoft. We set some flags and put a nicer icon in, which anyone could do or not do themselves when running Microsoft's build vscode build scripts.
