### ISSUE TITLE
Updating VSCodiumUserSetup (x64) is blocked by a false error

### ISSUE THREAD

**Issue by ealap** [VSCodium/vscodium#115]
**Describe the bug**
An error occurs when updating VS Codium x64 (user setup)

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Precondition:
- VS Codium x64 (user setup) is already installed

1. Run `VSCodiumUserSetup-x64-1.xx.x.exe` to update current installation

**Expected behavior**
Installation setup begins

**Actual behavior**
An error message blocks installation.
![image](https://user-images.githubusercontent.com/15620712/56040305-afdd2b00-5d68-11e9-8261-a85194f31f88.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture: x64
 - Version: 1.33.1

**Additional context**
I have seen this issue since v1.32.0 and my only workaround is to uninstall the previous version first before updating to latest.

**Comment by stripedpajamas** [comment]
Hi @ealap 

Sounds pretty weird. I did a little digging into the `vscode` repo to see what the logic is around throwing that error. The message is [here](https://github.com/Microsoft/vscode/blob/master/build/win32/code.iss#L1038) in the Inno setup config file. It looks like the logic is roughly "if the 'other' architecture's uninstall key exists in the registry, throw the error". 

It gets the other architecture's uninstall key from a passed in parameter called `IncompatibleArchAppId` (passing it in [here](https://github.com/Microsoft/vscode/blob/master/build/gulpfile.vscode.win32.js#L93)). That in turn is populated from the `product.json` file (see [here](https://github.com/Microsoft/vscode/blob/master/build/gulpfile.vscode.win32.js#L67)).

The `product.json` file seems to be the culprit to me. While it has distinct app IDs for `win32` and `win32x64`, these only apply to the System setup. The User setup (which you mentioned you used) has the same app IDs for both architectures [are the same](https://github.com/Microsoft/vscode/blob/master/product.json#L14-L15).

Can you use the System setup?

**Comment by ealap** [comment]
> Can you use the System setup?

Yes, I have tried installing and updating via System setup, and it works just fine. Though I still prefer using the User setup.

**Comment by stripedpajamas** [comment]
Can you confirm how you tested this with VS Code? Since the behavior looks to me to be written write into their `product.json` I would expect the same thing to happen.

**Comment by ealap** [comment]
It's basically the same steps with VS Code, I just run the latest User setup installer on top of an existing older version.

**Comment by stripedpajamas** [comment]
Ok. Thank you for your input on this. I will try to reproduce it myself and troubleshoot this.

**Comment by stripedpajamas** [comment]
Alright-- I believe I've gotten to the root of the issue. At build time, behind the scenes, Microsoft updates the app ID values in the `product.json` file so that each installer (System 32 and 64, User 32 and 64) have different app IDs. I think it's in violation of Microsoft's license for me to reproduce a part of their proprietary `product.json` here to show you.

The ones that are in the `vscode` repo that VSCodium is blindly using:
```javascript
  "win32AppId": "{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}",
  "win32x64AppId": "{{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}",
  "win32UserAppId": "{{C6065F05-9603-4FC4-8101-B9781A25D88E}",
  "win32x64UserAppId": "{{C6065F05-9603-4FC4-8101-B9781A25D88E}"
```

The important part being that all of their updated IDs are unique, which is why their product doesn't fall into the logic block that puts up the error message you are seeing. 

The resolution for this will be for VSCodium to also update app IDs at build time. I think we should leave all the app IDs the same except for the last one. That way we are changing as little as needed to get the functionality we expect. 

I will prepare the PR to update `product.json` at build time and then future versions of VSCodium shouldn't suffer from this bug.

**Comment by stripedpajamas** [comment]
(anyone can do this if they get to it before I do; in `build.sh` we modify `product.json` and we want to modify it further by altering the `win32x64UserAppId` to a random but consistent GUID)
