### ISSUE TITLE
MS crash reporter still enabled on clean install

### ISSUE THREAD

**Issue by evitalis** [VSCodium/vscodium#123]
**Describe the bug**
Microsoft crash reporting appears to still be enabled upon clean installation

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Download and install VSCodium
2. Check telemetry settings in VSCodium UI

**Expected behavior**
Should be disabled out of the box. I am certain this was mentioned as being off in the docs but cannot find the exact quote at this time.

**Screenshots**
https://i.imgur.com/1cjhq6X.png

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Architecture x64
 - Version 1.33.0+

**Additional context**

**Comment by stripedpajamas** [comment]
Good catch!! It looks to me like MS moved the location of the crash reporter setting so that our settings script misses it (https://github.com/VSCodium/vscodium/blob/11db2cfa65e4793cef3a2ac7e83542b93cda15ab/update_settings.sh#L5). Will need to find what file controls the default for that setting and update our script.

**Comment by evitalis** [comment]
Glad I could help. If it also helps I noticed this on a clean install on Fedora 29 but likely its the same issue as on Windows.
