### ISSUE TITLE
Issue with liveshare extension.

### ISSUE THREAD

**Issue by AnatoleLucet** [VSCodium/vscodium#128]
**Describe the bug**
So when i try to join a live share i simply get this error : 
```
[VS Code] Joining collaboration session: [ms-vsliveshare.vsliveshare]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-vsliveshare.vsliveshare
```

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install the extension : Live share.
2. Join a session with an url.
3. And you should get the error.

**Desktop:**
 - OS: Ubuntu 16.04
 - Architecture: x86_64
 - Version: 1.33.0

**Additional context**
I've tried to solve it with [this issue](https://github.com/MicrosoftDocs/live-share/issues/262) but it dosen't work.

**Comment by stripedpajamas** [comment]
Hi @AnatoleLucet -- thank you for this report 👍 

I tried out LiveShare just now and got the error you experienced as well. But when I added `"ms-vsliveshare.vsliveshare"` to the `"extensionAllowedProposedApi"` section of the `product.json` file, LiveShare worked properly. 

Can you comment the path to your `product.json` file as well as the contents of it? If we find that we can get it working by modifying the `product.json` file, we can patch the build so future versions don't need to be manually modified.

**Comment by AnatoleLucet** [comment]
Hi @stripedpajamas where can i find my 'product.json' ? Or maybe i need to create it ?

**Comment by AnatoleLucet** [comment]
Ok i found it, it was at this path : `/usr/share/vscodium/resources/app/product.json`
I've added `"ms-vsliveshare.vsliveshare"` in the `"extensionAllowedProposedApi"` array and it works fine !
Thanks you a lot @stripedpajamas

**Comment by gseroul** [comment]
HI guys,
I just installed and try v0.34 and I had the same issue. Modifying the file product.json solved the problem, should be in release no ?
I am on windows 10, vscodium 1.33.1
Otherwise superb extension !  Congratulations to author !

**Comment by GitMensch** [comment]
> I just installed and try v0.34 and I had the same issue. Modifying the file product.json solved the problem, should be in release no ?

No. Because using this extension is covered by its own license which forbids to use it in every "not microsoft controlled binary". See https://marketplace.visualstudio.com/items/MS-vsliveshare.vsliveshare/license and https://microsoftdocs.github.io/live-share/license/eula.html - so it should be nothing that comes with the install.

**Comment by toddewilliams** [comment]
@GitMensch is absolutely correct. You're simply forbidden from using Live Share in VSCodium.

Additionally, you're not allowed to install ANYTHING from the extension marketplace into a non-Microsoft product according to that site's [terms of use](https://cdn.vsassets.io/v/M146_20190123.39/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf). See section 1b.

VSCodium is basically not at all welcome here and and closing this bug was the correct action.

That said, you have a better option anyway.

Go install CodeTogether from the website or the Open VSX Marketplace and you'll be able to live share from VSCodium or any other IDE based on the Code source (including VS Code). And you'll be able to share between Eclipse-based and IntelliJ-based IDEs too. You'll have freedom of choice to use any of your favorite IDEs and still live share your development sessions between them all. And yes, there is a totally zero cost plan because we all love free.

Disclaimer: CodeTogether is a product of Genuitec and I not only work there, I co-founded it over 20 years ago to build professional tools for other software developers. However, I'm posting here simply because y'all need to know the truth about why you'll never see Microsoft support VSCodium and to welcome all y'all to our freedom of choice alternative.

**Comment by acoolstraw** [comment]
you are a fucking loser todd
