### ISSUE TITLE
why the update system is so bad

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [VSCodium/vscodium#1289]
i have to replace all of the files for each new update

**Comment by H-A-M-G-E-R** [comment]
or using the installer manually

**Comment by NERBLER09** [comment]
If you are on a linux system and installed VSCodium using the native package manager or native package format you have to update via the package manager or a GUI software manager.

**Comment by trymeouteh** [comment]
For Ubuntu, is the best package version to use the @paulcarroty] deb repo or the Flatpak?

**Comment by daiyam** [comment]
Except his ranting, we know nothing of @H-A-M-G-E-R's issue. Unless, we have some info, we can't help him. It might be a know issue, a new issue, or a bad use of the package manager.

**Comment by Crystal-RainSlide** [comment]
Also see: https://github.com/microsoft/vscode/issues/56326

**Comment by daiyam** [comment]
@Crystal-RainSlide Zip installs are for those who like to manage their apps by hands. So the updates should be the same.
For Windows, you have the `.exe` and `.msi` which are supporting updates (since this month for `.msi`). You could use `winget` and `choco`.
For Linux, you have several package managers available which are managing the updates of VSCodium (like any other apps).

Unless, there is a specific issue/example, I think this is a non-issue.
