### ISSUE TITLE
Automatic import vscode configuration / extensions

### ISSUE THREAD

**Issue by camlafit** [VSCodium/vscodium#131]
**Provide an option to import original vscode configuration**

Hello,

I've tried to migrate from orginal vscode  to vscodium but I need to reinstall all extensions and redo configuration.

Could be nice to have on first installation to copy previous environnement if existing.
In debian use case configuration could be at least :
* cp -bar /home/[user]/.config/Code /home/[user]/.config/VSCodium 
* cp -bar /home/[user]/.vscode /home/[user]/.vscode-oss

Manual configuration explained in doc could be automated in part.

I presume could be done same with Linux configuration.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

Documentation looks incomplete.

**Desktop (please complete the following information):**
 - OS: [ Debian Stretch ]
 - Architecture [ x64 ]
 - Version [ any]

**Comment by stripedpajamas** [comment]
Hi @camlafit, thanks for logging this issue.

VSCodium is just a manual build of the `vscode` repo. Since Visual Studio Code doesn't have any automatic searching/copying of existing extensions or configuration on first install/run, VSCodium won't either. Users migrating away from Visual Studio Code can either follow the manual instructions or use an extension like [`code-settings-sync`](https://github.com/shanalikhan/code-settings-sync) which does the work for them.

Please let me know which parts of the documentation are incomplete so we can get that straightened out -- PRs always welcome as well 🙏

**Comment by camlafit** [comment]
Hello

Thanks for you're reply :) 
In this specific case, move locally vscode to vscodium has no sense to use an external module to share data. And could have a problem about privacy usage (it's an another problem)

Looks normal that feature is not implemented in vscode as it's only related about migration process to vscodium.

Finally looks have a sense to update Wiki to explain migrate process, to take in care .config directory. I could try to propose a PR about this :)

Thanks

**Comment by evitalis** [comment]
I have some mixed feelings on this. As noted by @stripedpajamas this is just a manual build of the upstream project. Adding additional code can potentially introduce complications in this process if the upstream project changes, and creates more manual work during the upgrade process for VSCodium.

It may be better to just clarify the migration process documentation since sometimes its is nice to start with a clean slate. Users may make changes they no longer need or remember why they were made in the first place.

**Comment by stripedpajamas** [comment]
This project needs to stay as simple as possible to enable more transparency. As such, we don't want to introduce additional code such as automatically copying existing configurations. 

If the Docs page can be improved, please put a PR in or open a new issue with details on how you think it could be improved so that someone else can jump on it.
