### ISSUE TITLE
MS Python extension now requaried telemetryLogger

### ISSUE THREAD

**Issue by stalkerg** [VSCodium/vscodium#1400]
Can't use the python extension anymore. 

```
ERR Extension 'ms-python.python' wants API proposal 'telemetryLogger' 
```

**Comment by stalkerg** [comment]
Thanks!

**Comment by Razique** [comment]
I encountered this issue. The fix consists in:

1. Quitting VSCodium
2. Updating your `product.json` by adding `telemetryLogger` per https://github.com/VSCodium/vscodium/commit/d6e7ae1f6f85aa2439d3b5f1a44aedcc4e158982
3. Restarting VSCodium
4. You should see an update for the `ms-python` (PyLance) extension. Install it
5. The language server should now start.

**Comment by stalkerg** [comment]
@Razique working! I did all this before except update `ms-python`.  :)

**Comment by daiyam** [comment]
Could you test the latest Insiders version (https://github.com/VSCodium/vscodium-insiders/releases/tag/1.77.0.23062-insider, still building)?
I've updated to take the latest API proposals (directly from the VSCode app) but I've seen that `telemetryLogger` was missing, so I wonder...
If you can validate it is an issue or not as soon as possible since I'm going to release a new stable version.
