### ISSUE TITLE
Processes stay open when app is killed via SIGTERM

### ISSUE THREAD

**Issue by MoralCode** [VSCodium/vscodium#1407]
Type: <b>Bug</b>

I probably need to get more RAM for my computer, but havent gotten around to it yet.
To prevent my (linux) system locking up in low-ram situations (while waiting for kernel OOM to kick in), i use [earlyoom](https://github.com/rfjakob/earlyoom) (id rather have a couple programs get closed quickly than have everything hang).

Sometimes this results in VSCodium getting closed by earlyoom (which it seems like it does using SIGTERM, one of the less aggressive signals). When this happens, it pretty much always only closes the GUI, but leaves a few dozen processes still open and taking up memory. I usually go into system monitor and have to manualy quit those processes for VSCodium to release its memory.

I realize this problem may be solved by a few things:
- buy more ram
- somehow configure earlyoom to detect all of these processes (not sure if its possible to do, havent tried yet)
- update VSCodium/VSCode to detect such signals that the app should and correctly exit or shutdown all processes

VSCodium version: VSCodium 1.74.3 (f8b9aeda40058455453f1298fd606caf6ff8d675, 2023-01-10T19:39:41.226Z)
OS version: Linux x64 5.15.0-58-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|7, 4, 3|
|Memory (System)|15.42GB (3.33GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
dart-code|Dar|3.58.0
flutter|Dar|3.58.0
xml|Dot|2.5.1
gitlens|eam|13.2.0
ginfuru-vscode-jekyll-syntax|gin|0.1.1
tcl-language-support|go2|0.1.2
docthis|joe|0.7.1
vscode-clangd|llv|0.1.23
python|ms-|2022.20.2
autodocstring|njp|0.6.1
vetur|oct|0.36.1
vscode-jest|Ort|5.2.3
rust|rus|0.7.8
sass-indented|syl|1.8.23
pony-ssh|thi|0.6.0
latex-support|tor|3.10.0
markdown-all-in-one|yzh|3.5.0

</details>

**Comment by rniem379349** [comment]
I have been experiencing a similar problem lately - in particular, I found that Codium doesn't kill integrated bash processes when the app is closed. I found this by running `ps aux | grep "codium"` and noticing a few lingering `shellIntegration-bash.sh` processes after having closed Codium. 
Personally, I found this to be a problem not because of the unnecessarily used up memory (just a few MB per unclosed shell), but more because those lingering processes wouldn't respond to SIGTERM signals on system shutdown, which slowed down my shutdown times significantly on Linux (Fedora 36) - from just a few seconds to well over a minute (Fedora waits the standard 90 seconds for the processes to respond to SIGTERMs, which they don't). Not sure if this is the same issue as OP has, but it seems to be related. 

As for this issue, there seems to be a fix out for VSCode already: 
https://github.com/microsoft/vscode/issues/174956
https://github.com/microsoft/vscode/pull/176819
This was only merged in yesterday, so now it's a matter of waiting for this fix to be incorporated into Codium - I hope it happens ASAP

**Comment by daiyam** [comment]
If the Insiders release is fixed, it can be soon for that version.

**Comment by yoryov** [comment]
Hi, everyone

Facing the same issue here with VS Codium version 1.76.2, the processes  `/usr/bin/bash --init-file /usr/share/codium/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh` doesnt finish when I close the Codium app and I need to kill the process with a `kill -9 PID` because my laptop can't turn off and keeps waiting approximately for 1 and half minutes.

Does anyone know when this issue might be fixed?

**Comment by daiyam** [comment]
It's an upstream issue and should be fixed in `1.78` (ref: https://github.com/microsoft/vscode/issues/174956#issuecomment-1494581637)

**Comment by yoryov** [comment]
Thanks!
