### ISSUE TITLE
Updater is not signed

### ISSUE THREAD

**Issue by Verequus** [VSCodium/vscodium#1419]
**Describe the bug**
The updater executable is not signed. So it is not possible to create policies in regards to this executable.

**Please confirm that this problem is VSCodium-specific**
- [ X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Not applicable.

**Expected behavior**
The updater is signed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
In my company, the administration rights are handled stringently. The software which can be easily installed is placed into a special repository, which is updated manually by the IT. Software that is frequently updated places a hard burden on the staff. So alternatively, it is possible to make special exceptions to certain executables. But for that, these files need to be signed properly.

**Comment by GitMensch** [comment]
The installer is not signed either, because - as I see it - no one sponsored a code signing certificate along with adjusting the CI to use it for code signing. This is actually a duplicate as #174 (after I've reopened it...), so please feel free to discuss there.
You may want to discuss with your IT staff to sponsor the certificate and the work to integrate it if it is important to you.
