### ISSUE TITLE
Enable Experiments is enabled by default

### ISSUE THREAD

**Issue by evitalis** [VSCodium/vscodium#145]
**Describe the bug**
The setting `Enable Experiments` was enabled on a brand new clean install on Fedora 30.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. On a Fedora 30 installation install VSCodium from the GitLab repo RPM
2. Go to Settings
3. Expand `Workbench` and check `Enable Experiments` and it will be checked

**Expected behavior**
This setting should be turned off as the description is:

> Fetches experiments to run from a Microsoft online service.

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Architecture x64
 - Version 1.33.1

**Comment by stripedpajamas** [comment]
Boooooooooooooo 👎 

Good catch @evitalis, thank you for reporting this. It should be easy enough to default that to off since we already have the function to do so. I'll take care of it.

**Comment by evitalis** [comment]
I also found the Natural Language setting is also on by default. Should I add that to a separate bug report?

**Comment by stripedpajamas** [comment]
Well... currently there is this information in the doc: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#getting-all-the-telemetry-out which acknowledges the NLP stuff and the other settings that call home to MS as something users could consider. Experiments might even fall into this category too as more of a user issue. 

Microsoft is very clear in that they've tagged all of these with `usesOnlineServices` -- I'm wondering if the VSCodium contract of "disabling telemetry" covers other `usesOnlineServices` settings, and where exactly that line falls.

**Comment by evitalis** [comment]
For the discussion, would it be worth adding some other known (popular) extensions that send data to Microsoft? I know I use a Python extension I think is developed by them but seems the most maintained and popular. Not sure if it has telemetry in it.

**Comment by stripedpajamas** [comment]
The question is whether or not VSCodium should disable all settings that "use online services" by default. These are:

- Workbench: Enable Experiments
- Workbench > Settings: Enable Natural Language Search
- Update: Enable Windows Background Updates (this will probably need to be turned on when we get auto update support working)
- Update: Show Release Notes
- Extensions: Auto Check Updates
- Extensions: Auto Update
- Extensions: Show Recommendations Only On Demand (default off)
- Telemetry: Enable Crash Reporter
- Telemetry: Enable Telemetry

Currently, VSCodium disables the two Telemetry settings before building (https://github.com/VSCodium/vscodium/blob/master/update_settings.sh#L3-L4). 

This issue was opened up regarding Enable Experiments. We need to figure out where the line is on setting the defaults for these settings.

(@evitalis -- the Python extension built by MS does send telemetry, but purportedly honors the Enable Telemetry settings flag -- see [here](https://github.com/Microsoft/vscode-python#data-and-telemetry))

**Comment by korlando7** [comment]
Why not just disable all of them?

**Comment by evitalis** [comment]
@korlando7 Disabling everything may break some functionality so I think the team is trying to be cautious about that. Additionally some users may want some of the settings on, and while I prefer things to be opt-in not out, the world prefers the opposite.

**Comment by DavidOliver** [comment]
I would have thought that if someone has bothered to use an alternative to Microsoft's binaries they would be part of the prefer-opt-in camp.

**Comment by stripedpajamas** [comment]
Thanks for the feedback, everyone. For now, VSCodium is going to remain true to what is said in the readme: "telemetry is disabled". The other options within VSCodium that use online services can be disabled as per the preference of the user.

The [docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#getting-all-the-telemetry-out) makes it clear that there are options that connect to Microsoft's services and that they can all be disabled if desired. 

In regard the original request: `Enable Experiments` does not call out to a Microsoft service if there is no `experimentsUrl` in the product.json file (see the code [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/experiments/node/experimentService.ts#L173)). As VSCodium does not set the `experimentsUrl` at build time, the `Enable Experiments` option is irrelevant.
