### ISSUE TITLE
Could you discuss in README if telemetry features are included or disabled in builds?

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [VSCodium/vscodium#15]

**Comment by stripedpajamas** [comment]
@WIZARDISHUNGRY can you check out #16 and see if the change helps clarify?

**Comment by WIZARDISHUNGRY** [comment]
Sure, I guess my question is "what (if any) telemetry/tracking" exists in the unmodified VSCode sources? Does the telemetry tracking only get added as part of the MS build process? [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium) has to go through a lot of hoops to rip out all the google stuff.

I know there's privacy concerns around the extension store, etc. but a clear statement on the telemetry code itself ("Telemetry is enabled by a build flag which we do not pass", etc.) would be cool.

**Comment by stripedpajamas** [comment]
Understood. As far as I know, no tracking exists explicitly in the unmodified VSCode sources, and telemetry needs to be explicitly enabled with its destination URLs at build time. It would be great to get some more opinions on that, since all of the code is public. 

This [comment](https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005) in the vscode repo says this:

> When we build Visual Studio Code, we do exactly this. We clone the vscode repository, we lay down a customized product.json that has Microsoft specific functionality (telemetry, gallery, logo, etc.), and then produce a build that we release under our license.
> 
> When you clone and build from the vscode repo, none of these endpoints are configured in the default product.json. Therefore, you generate a "clean" build, without the Microsoft customizations, which is by default licensed under the MIT license (note, i made this commit to help make this more clear).

I will give another pass at the README with your suggested text.

**Comment by stripedpajamas** [comment]
@WIZARDISHUNGRY updated readme and to be more explicit about us not passing the telemetry flag #16
