### ISSUE TITLE
[RFE] FreeBSD support

### ISSUE THREAD

**Issue by lapo-luchini** [VSCodium/vscodium#151]
Since now FreeBSD has a [working Electron port](https://github.com/tagattie/FreeBSD-Electron) (even if not yet officially into FreeBSD repositories) I'd like to try and use an updated VSCodium there.
(right now I'm using the «all-in-one compile» [VSCode 1.26.0 by prash](https://github.com/prash-wghats/Electron-VSCode-Atom-For-FreeBSD/releases/tag/vscode_v1.26.0), but using 1.33.1 would of course be nicer)

**Desktop:**
 - OS: FreeBSD 12.0
 - Architecture amd64
 - Version 1.33.1

**Comment by stripedpajamas** [comment]
Hi @lapo-luchini 👋That's exciting news!! I know people have been wanting `vscode` FreeBSD support for years now. 

If it involves messing with the `vscode` sources much to get it working, it is probably out of scope of this project. If it only requires some cleverness with the build process itself, it is probably in the scope of this project. That being said, I see two paths forward:

- you get a build script working that produces vscode/VSCodium artifacts usable by FreeBSD users and we link to it (if the changes heavily affect `vscode`) or merge it in (if the changes are build-process related)
- Microsoft hears about the working electron port and starts supporting FreeBSD themselves, and as a consequence VSCodium support is automatic (since VSCodium is just a an automated build of `vscode`)

**Comment by lapo-luchini** [comment]
Actually… the same @tagattie that ported Electron (now [in the official Ports](https://www.freshports.org/devel/electron4/)) is also working on a not-yet-"clean enough" to be committed, but already working nicely [FreeBSD Port of VSCode](https://github.com/tagattie/FreeBSD-VSCode). =)
AFAICT most of [the needed patches](https://github.com/tagattie/FreeBSD-VSCode/tree/master/editors/vscode/files) seems to be oriented towards «in this regard treat FreeBSD just like Linux».

**Comment by stripedpajamas** [comment]
I am uncertain about the direction of this issue @lapo-luchini -- perhaps when the port is no longer experimental, we can link to it from the README for other FreeBSD users?

**Comment by xxyzz** [comment]
The port mentioned above is in the FreeBSD ports now. Typing the following command will install it.
```
pkg install vscode
```
