### ISSUE TITLE
Provide REH & web builds

### ISSUE THREAD

**Issue by adamreichold** [VSCodium/vscodium#1518]
I think this is basically a follow-up to #1099.

While the REH builds are great to interface with an existing VS Code installations, I very constrained environments where one is unable to even install a local build of VS Codium, it would be great to have access to the web variant of the REH builds mention in https://github.com/VSCodium/vscodium/issues/1099#issuecomment-1146356434 so that the setup could be fully self-contained, i.e. the web-variant of REH is deployed and made accessible via secured TLS connection and the user can immediately start working by accessing the web UI served by the REH host via a well-known URL.

To support this use case, I would be grateful if the web-variant of the REH builds could be included in the CI artifacts as well. (I think they could theoretically just replace the plain REH builds as they offer a proper superset of their functionality?)

**Comment by SuhasHebbar** [comment]
I had played around with gitpod's [openvscode-server](https://github.com/gitpod-io/openvscode-server) that has linux only builds of this for a while and had noticed that there are a few rough edges for day to day use.

code server stores user settings and client extensions (like VSCodeVim) in indexdb. With VSCodium you can just sync settings.json, keybindings.json and other files via syncthing or some other method like [vscode-sync-settings](https://github.com/zokugun/vscode-sync-settings). This won't work for VSCode web.


So, if you are working on two remote servers serverA.domain and serverB.domain you will have to copy your config and install extensions separately and manually on both of them. 

Adding a new machine or changing config can be a pain since you will have to propagate the changes manually by yourself clicking around in the UI. If you start using a new system or a different browser same issue of repeating the manual setup.

All that said I would love to have VSCodium web server builds. The option being available could encourage folks to fix its rough edges. Maybe someone would then add support for web builds in [vscode-sync-settings](https://github.com/zokugun/vscode-sync-settings).

**Comment by joelpurra** [comment]
Just to chime in on a minor part of this suggestion:

> (I think they could theoretically just replace the plain REH builds as they offer a proper superset of their functionality?)

I do not consider a `-web` build to be a superset; it has a very different use-case, and is not an improvement for _all_ REH users. Having an _additional_ `-web` build artifact for browser usage is of course fine.

**Comment by MacWeber** [comment]
+1 for this feature!

**Comment by HoboDev** [comment]
I would like to +1 for web builds.

**Comment by daiyam** [comment]
Hi, the `reh-web` binaries are available at https://github.com/VSCodium/vscodium-insiders/releases/tag/1.93.0.24231-insider. Can you test it? Thx

**Comment by adamreichold** [comment]
I am sorry for not posting earlier.

I still have this on my to-do list but did not find the time yet to reconfigure the whole TLS-tunnel-based setup. I also think the probability of issues is low as basic functionality worked when trying upstream VS Code (which we however do not want to use due to privacy concerns) some time ago and I will just have to file a new issue if I find any problems using the `reh-web` builds.

In any case, thank you for working on this and making the option available to VS Codium users!
