### ISSUE TITLE
No Keyring found, after update to 1.8

### ISSUE THREAD

**Issue by RoccoRakete** [VSCodium/vscodium#1561]
**Describe the bug**
Error message:
"An OS keyring couldn't be identified for storing the encryption related data in your current desktop environment."
When trying to connect to github

**Please confirm that this problem is VSCodium-specific**
- [ X ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ X ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Trying to do any git actions related to a repository

**Expected behavior**
Cium should detect the keyring

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Architecture X64
 - Version 1.80.0
 - App Manager AUR
 - Sandboxed no

The GitHub token is in fact stored in the keyring.

**Comment by slokhorst** [comment]
Same issue here, with a few remarks:

* This was introduced in 1.80.0, not 1.8
* This also happens with the Microsoft Visual Studio Code build
* If I click "show documentation", nothing happens

**Comment by RoccoRakete** [comment]
> Same issue here, with a few remarks:
> 
>     * This was introduced in 1.80.0, not 1.8
> 
>     * This also happens with the Microsoft Visual Studio Code build
> 
>     * If I click "show documentation", nothing happens

VSCode 1.80.0 is working perfectly fine for me.

**Comment by slokhorst** [comment]
Okay, my issue probably isn't a VS Code issue. It's just that my keyring isn't being autodetected.

After seeing the troubleshooting guide (not sure why I couldn't open that before), and using `code --password-store="gnome"`, it works fine as before. I just remembered I had the same issue with Google Chrome, where I had to use the same command line argument to manually specify the password store to get it to work.

(I'm using Openbox with Gnome Keyring on Arch Linux.)

**Comment by szilvesztercsab** [comment]
**Reproducible** in VS Code version `1.80.0` on `Debian 11 (bullseye)` installed via official `.deb` package.

Plus, now my browser doesn't seem to open from VS Code anymore either.

**Downgraded** to `1.79.2` like so:
```sh
sudo apt install code=1.79.2-1686734195
```
...and it works again now.

---

Has to do with [this](https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues:~:text=NOTE%3A%20This%20section%20applies%20to%20VS%20Code%20version%201.80%20and%20higher.%20In%201.80%2C%20we%20moved%20away%20from%20keytar%2C%20due%20to%20its%20archival%2C%20in%20favor%20of%20Electron%27s%20safeStorage%20API.) (_"In 1.80, we moved away from [keytar](https://github.com/atom/node-keytar), due to its archival, in favor of Electron's [safeStorage AP](https://www.electronjs.org/docs/latest/api/safe-storage)"_).

---

**I just couldn't live with a previous version, so I tried [this](https://github.com/microsoft/vscode-docs/blob/vnext/docs/editor/settings-sync.md#other-linux-desktop-environments) and managed to fix the issue.** 

Thanks @slokhorst for pointing me in the right direction.

**Comment by BaigHack3rss** [comment]
> **But, I just couldn't live with a previous version, so I tried [this](https://github.com/microsoft/vscode-docs/blob/vnext/docs/editor/settings-sync.md#recommended-configure-the-keyring-to-use-with-vs-code) (hardcoding `"password-store": "gnome"` in `argv.json`) and managed to fix the issue.**
> 
> Thanks @slokhorst for pointing me in the right direction.

Editing the argv.json works!! I'd consider this issue closed.

**Comment by RoccoRakete** [comment]
> > **But, I just couldn't live with a previous version, so I tried [this](https://github.com/microsoft/vscode-docs/blob/vnext/docs/editor/settings-sync.md#recommended-configure-the-keyring-to-use-with-vs-code) (hardcoding `"password-store": "gnome"` in `argv.json`) and managed to fix the issue.**
> > Thanks @slokhorst for pointing me in the right direction.
> 
> Editing the argv.json works!! I'd consider this issue closed.

Yep this does work.

**Comment by fedehc** [comment]
Somehow, changing argv.json with `"password-store": "basic"` works for me too...
