### ISSUE TITLE
Cant install on arch because Yarn

### ISSUE THREAD

**Issue by NaufalF22** [VSCodium/vscodium#1565]
**Describe the bug**
I just want to install vscodium on arch and just error

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Install vscodium on arch like usual "yay -S vscodium"

**Expected behavior**
Get install

**Screenshots**
![image](https://github.com/VSCodium/vscodium/assets/63091744/c7368907-0e94-4484-ae0e-66a8cd14adb3)

**Desktop (please complete the following information):**
 - OS: Latest arch linux
 - Architecture x64
 - Version latest
 - App Manager AUR
 

**Additional context**

**Comment by Exidex** [comment]
Had the same issue when trying to install "vscodium". "vscodium-bin" works fine though and it is recommended here https://github.com/VSCodium/vscodium#install-on-arch-linux

**Comment by daiyam** [comment]
`vscodium-bin` uses the tarball while `vscodium` is re-compiling.

@Exidex Do you have the same error?

**Comment by Exidex** [comment]
@daiyam no actually,  I had different one 
```
error: failed to commit transaction (conflicting files)
yarn: /usr/bin/yarn exists in filesystem
yarn: /usr/bin/yarnpkg exists in filesystem
Errors occurred, no packages were upgraded.
```

**Comment by daiyam** [comment]
@Exidex It seems that there is conflict on`yarn` binary when installing the the package `yarn` (it's a make dependency, removed when vscodium is built)
Do you have any other packages which have installed that binary?

@cedricroijakkers Hi, do you know how the error of @Exidex could happen?

**Comment by Exidex** [comment]
@daiyam looking at logs. Using yay I installed `extra/yarn` then installed `vscodium` then removed yarn but the binary seems to be still present, do not remember what set whether to remove build dependencies or not.  

Here's my [pacman.log](https://github.com/VSCodium/vscodium/files/12138356/pacman.log) if you want to debug

**Comment by NaufalF22** [comment]
> Had the same issue when trying to install "vscodium". "vscodium-bin" works fine though and it is recommended here https://github.com/VSCodium/vscodium#install-on-arch-linux



> Had the same issue when trying to install "vscodium". "vscodium-bin" works fine though and it is recommended here https://github.com/VSCodium/vscodium#install-on-arch-linux

So i also ask on yarn github and they said https://github.com/yarnpkg/berry/issues/5579#issue-1805524698

**Comment by cedricroijakkers** [comment]
First of all, the fact that `vscodium-bin` works but `vscodium` not is pretty normal, since the former just downloads pre-compiled binaries and installs them on the OS, while the second builds the code from source and then installs it. `yarn` is not needed to download the binaries or run them, so there is no dependency on it, so that works fine.

Secondly, I have the `yarn` package installed on my OS, which is in the `makedepends` list for `vscodium`, so it is normal that I have the executable in my PATH list:

```shell
$ which yarn
/usr/bin/yarn
```

Now, looking at the error in the screenshot from OP, it seems like there was an error 404 when downloading an NPM package? This should be a temporary issue, since I just tried to build the package with `yay -S vscodium` and that worked fine. Can you try it with a CleanBuild (answer `Y` to the first question `yay` asks when building)?

Next, the following error:

```
error: failed to commit transaction (conflicting files)
yarn: /usr/bin/yarn exists in filesystem
yarn: /usr/bin/yarnpkg exists in filesystem
Errors occurred, no packages were upgraded.
```

What I think is going on here, as you already mentioned, you tried uninstalling the `yarn` package but some executables were left on your filesystem, causing the package manager to bail out because files already exist that were installed outside of the package manager. Since `yarn` is a required package to build `vscodium`, the package manager thinks `yarn` is not yet installed on disk, tries to install it, and then fails because it already finds files on the disk which it would normally be installing. Luckily, there is an `--overwrite` option in `pacman` to force the package manager to ignore the files on disk and overwrite them with the ones it wants to install. So, try the following:

First, force a re-install of `yarn`, overwriting the files already present on the disk with the ones from the official package:

```shell
yay -S --overwrite "*" yarn
```

Then, try to build `vscodium` again as usual:

```shell
yay -S vscodium
```

When `yay` asks if you want to CleanBuild, answer `Y`. As long as your internet connection is stable and all packages can be downloaded, it should work.
