### ISSUE TITLE
Missing 32-bit package for 1.33.1 release

### ISSUE THREAD

**Issue by Thilas** [VSCodium/vscodium#157]
Hi,

It seems that [1.33.1 release](https://github.com/VSCodium/vscodium/releases/tag/1.33.1) no longer provides the system-wide Windows 32-bits installer (only the user 32-bits one as well as both 64-bits ones).

I know for sure that until yesterday this installer was listed. Do you know what happened?

Thanks

**Comment by stripedpajamas** [comment]
That is very weird. Two PRs were merged in yesterday, but the builds shouldn't (don't?) have the ability to remove artifacts from the latest release/tag. The builds themselves are supposed to be no op if the artifacts already exist. Something must be misconfigured in our Azure pipelines. I will look into it, but I may need to delete the Windows 32-bit artifacts and re-queue that build to repopulate.

**Comment by stripedpajamas** [comment]
It appears to be a sad domino effect of problems. The below is scraped from the [build logs](https://dev.azure.com/vscodium/VSCodium/_build?definitionId=1) and the [release logs](https://dev.azure.com/vscodium/VSCodium/_release?definitionId=1) although I don't know if those are accessible to the public (a reason to move off of Azure).

- when the build checked to see if the windows 32-bit artifacts already existed, Github had a server error:
  ```
  Github response: {   "message": "Server Error" }
  VSCodium assets: null
  Release assets do not exist at all, continuing build
  ```
- after building, it did notice the asset already existing during upload, and it is set to replace existing assets:
  ```
  2019-05-13T16:27:27.6758946Z Found duplicated asset: VSCodiumSetup-ia32-1.33.1.exe
  2019-05-13T16:27:27.6759460Z Deleting duplicated asset...
  2019-05-13T16:27:28.1404934Z Deleted duplicate asset: VSCodiumSetup-ia32-1.33.1.exe
  2019-05-13T16:27:28.2452838Z Uploading asset VSCodiumSetup-ia32-1.33.1.exe - 0% - 192.0 KB/s
  ...
  2019-05-13T16:27:37.8398322Z Uploading asset VSCodiumSetup-ia32-1.33.1.exe - 100% - 4.1 MB/s
  ```
- but when it was done uploading, the release did not have that file
  ```
  Finish - Release URL: https://api.github.com/repos/VSCodium/vscodium/releases/16708010
  ```

I'm guessing something went wrong with the upload, but it had already deleted it. I will remove the Windows assets and kick off the build again so that they are recreated.

**Comment by stripedpajamas** [comment]
Should be good now

**Comment by Thilas** [comment]
Confirmed. Thanks!
