### ISSUE TITLE
File dialog open shows up under codium window

### ISSUE THREAD

**Issue by doonv** [VSCodium/vscodium#1644]
**Describe the bug**
When opening a file, the dialog for opening a file shows under the codium window.

**Please confirm that this problem is VSCodium-specific**
This problem never happened to me while using VSCode.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open a file
2. The dialog is under the codium window.

**Expected behavior**
The dialog should be above the codium window.

**Desktop (please complete the following information):**
 - OS: Kubuntu 23.04
 - Architecture: x64
 - Codium Version: codium_1.82.2.23257_amd64
 - App Manager: Installed with the `.deb`
 - Sandboxed: No

**My workaround**
1. Right click on the titlebar > More Actions > Configure special window settings
2. Configure these window settings:
![image](https://github.com/VSCodium/vscodium/assets/58695417/f75e1a0b-af5b-443f-a8c9-ac397cb5139f)

**Comment by python-and-fiction** [comment]
I try it on Kubuntu 23.04 in my VM.
I found that it's right when i open vscodium first time,the windows' order is main window first.
![kubuntu-2023-09-17-23-39-51](https://github.com/VSCodium/vscodium/assets/16256910/4123ba00-cdaf-4bbe-b9cd-c47b7da2628a)
But when i click open folder after close FileChooseDialog,the windows' order is FileChooseDialog first.The issue occuers.
![kubuntu-2023-09-17-23-40-27](https://github.com/VSCodium/vscodium/assets/16256910/3eee67db-4620-4a68-9673-f7bbb02a7bd7)
The same issue doesn't occuer in vscode 1.82.2.

**Comment by pkra** [comment]
Just an FYI comment.

I've been encountering this on Gnome for as long as I can remember. It's an upstream issue, see https://github.com/microsoft/vscode/issues/146422 and https://github.com/electron/electron/issues/32857 (and possibly further up in Chromium).

I'm writing now because I happened to try out vscodium's flatpack version the other day and was surprised that it did not have this problem (though it also had differences in terms of focus management in the dialog which I struggled with).
