### ISSUE TITLE
Wayland: Both vscodium instances close if a second instance is started

### ISSUE THREAD

**Issue by PucklaJ** [VSCodium/vscodium#1693]
**Describe the bug**
I am working with a single instance of vscodium, but as soon as I start a second one to create a new window both seem to crash. It does not matter if I start a completely new instance or just open a new window through the command palette.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install vscodium from chaotic-aur
2. Start the first instance using `gtk-launch codium-wayland`
3. See that it works as usual
4. Start the second instance using `gtk-launch codium-wayland`
5. See that both instances instantly crash

**Expected behavior**
I should be able to open as many instances as my PC can handle. Using the xwayland version it works completely fine.

**Logs**
[First Instance (warning long log!)](https://github.com/VSCodium/vscodium/files/12897252/codium1.txt)

[Second Instance](https://github.com/VSCodium/vscodium/files/12897259/codium2.txt)

**Desktop (please complete the following information):**
 - OS: Artix Linux ([SamuraiOS](https://github.com/PucklaJ/SamuraiOS))
 - Architecture: x86_64
 - Version: 1.83.0
 - App Manager: pacman (chaotic-aur)

**Additional context**
The command executed for both logs was:
```
/usr/bin/codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland --unity-launch --verbose
```

**Comment by colemickens** [comment]
I am seeing this behavior, too.

Since this is the most recent Wayland issue, I'm also going to note. Lots of issues and hits from Google suggest that setting `"window.titleBarStyle": "custom"` is a fix for Wayland. 

While this worked for me a couple of days ago, I'm now find that VSCodium will not open at all with that option. Now, `"window.titleBarStyle": "native"` seems to allow me to open a single window. (Though to reiterate, I also have both windows crash if I try to open a second one, fortunately I don't really need that.)

It would be amazing if Wayland was made more of a priority for the VSCode devs to ensure there aren't regressions. Especially with so many distros moving towards Wayland by default, and with the various downsides of using XWayland.

**Comment by PucklaJ** [comment]
@colemickens I have set `"window.titleBarStyle": "custom"` and I can used it completely fine except for it crashing as soon as I open a new window

**Comment by TheRDavid** [comment]
> @colemickens I have set `"window.titleBarStyle": "custom"` and I can used it completely fine except for it crashing as soon as I open a new window

I am having the same issue, did you find a fix?

**Comment by PucklaJ** [comment]
@TheRDavid For me it just works right now. I am using the vscodium package from the chaotic-aur on Arch. The Exec entry in the .desktop file is the following:
```
/usr/bin/codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland --unity-launch %F
```
