### ISSUE TITLE
It's written vscode when you update

### ISSUE THREAD

**Issue by lorypelli** [VSCodium/vscodium#1694]
![image](https://github.com/VSCodium/vscodium/assets/87276663/7b5f4056-e21d-4492-855d-06a145453d9e)
As you can see from the image...

**Comment by daiyam** [comment]
Which medium?

**Comment by GitMensch** [comment]
@lorypelli Where does this happen? How did you initially installed Vscodium?

**Comment by lorypelli** [comment]
I installed from the official site and it happens since some versions

**Comment by lorypelli** [comment]
You had a different updater from microsoft one, but when you changed it, it broke (because the update gives also error)

**Comment by GitMensch** [comment]
What OS do you use? Where did you exactly installed it from (and which binary - there are 92 ones).

**Comment by lorypelli** [comment]
This is a new issue I'm noticing, and I can't update

**Comment by daiyam** [comment]
I haven't seen any `Visual Studio Code` remaining in the installed I've done.

Can you be a bit more specific on the version? Maybe a video of the install would be helpful.

**Comment by lorypelli** [comment]
> I haven't seen any `Visual Studio Code` remaining in the installed I've done.
> 
> Can you be a bit more specific on the version? Maybe a video of the install would be helpful.

I mean the updater when a new update comes out

**Comment by daiyam** [comment]
OK, I get the error `The program or feature "\??\C:\Users\User\AppData\Local\Temp\codium-stable-undefined-x64\CodeSetup-stable-5a21cd9bd26def06f1b56c50933f812884617855.exe" cannot start or run due to incompatibity with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available.` in the Windows Logs.

It's a path issue!

I will get the same error with `msiexec.exe /i .\VSCodium-x64-1.84.2.23314.msi`, while `msiexec.exe /i VSCodium-x64-1.84.2.23314.msi` will work
