### ISSUE TITLE
Consider a recurring donation option

### ISSUE THREAD

**Issue by c-mart** [VSCodium/vscodium#1870]
VSCodium is important for developers who choose to work with non-proprietary tools. It's important work to maintain this package (and also the broader ecosystem of extensions that provide a full-featured developer experience). [I try to make small but recurring donations](https://cmart.blog/cmart-philanthropy) to maintainers of projects that I want to help sustain.

I see https://github.com/VSCodium/vscodium/pull/122 added a Bitcoin wallet address, but it mentions @stripedpajamas who appears to no longer participate in the project. Ideally, I'd have a set-and-forget option for automatic recurring donations to @daiyam (and whoever else is actively involved as a maintainer).

Any of these would be great:
- [Liberapay](https://liberapay.com)
- [Open Source Collective](https://oscollective.org)
- GitHub Sponsors
- Patreon

Thanks for the work that you do!

**Comment by daiyam** [comment]
Hi @c-mart, you can find my donation links on my projects like https://github.com/zokugun/vscode-sync-settings

Glad that the project is helpful to you and thank you for your future contribution.

**Comment by stripedpajamas** [comment]
I recommend removing that Bitcoin address from the readme... it's only been used once and as said, it goes to my personal wallet. Added due to #118. The project is big enough imo to warrant something like Liberapay or Open Source Collective, but internally 99% of the work is done by @daiyam so it's probably not worth the hassle vs just donating to him them directly.
