### ISSUE TITLE
Cannot use Remote Development extension pack

### ISSUE THREAD

**Issue by qlan3** [VSCodium/vscodium#196]
**Describe the bug**
I cannot use Remote Development extension pack.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install Remote Development extension pack.
2. Press F1 and execute "Remote-SSH: Open configuration file" command.
3. See error "command 'opensshremotes.openConfigFile' not found" at the bottom right.

**Expected behavior**
The configuration file is open.

**Screenshots**
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/46080716/59382788-bb72b100-8d1b-11e9-8210-a6affea13819.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Architecture x64
 - Version 1.35.0

**Comment by JayAndCatchFire** [comment]
Can you please provide a link to this particular extension that isn't working?

**Comment by stripedpajamas** [comment]
I expect this is not working for very similar reasons as #128 -- the functionality is still considered a "proposal". As such, MS lists the allowed proposals in the product.json file pre-build. Their current list (1.35.0) is:

```
[ 'ms-vscode.references-view',
  'ms-vsliveshare.vsliveshare',
  'ms-vsliveshare.cloudenv',
  'ms-vsliveshare.cloudenv-explorer',
  'GitHub.vscode-pull-request-github',
  'Microsoft.vscode-nmake-tools',
  'atlassian.atlascode',
  'ms-vscode-remote.remote-containers',
  'ms-vscode-remote.remote-containers-nightly',
  'ms-vscode-remote.remote-ssh',
  'ms-vscode-remote.remote-ssh-nightly',
  'ms-vscode-remote.remote-ssh-edit',
  'ms-vscode-remote.remote-ssh-edit-nightly',
  'ms-vscode-remote.remote-ssh-explorer',
  'ms-vscode-remote.remote-ssh-explorer-nightly',
  'ms-vscode-remote.remote-wsl',
  'ms-vscode-remote.remote-wsl-nightly',
  'ms-vscode-remote.vscode-remote-extensionpack',
  'ms-vscode-remote.vscode-remote-extensionpack-nightly' ]
```

Our current list is:

```
[ 'ms-vscode.references-view', 'ms-vsliveshare.vsliveshare' ]
```

We can get Remote Development working by adding these proposals pre-build, as we are adding the liveshare proposal.

**Comment by qlan3** [comment]
Thanks!@stripedpajamas 
I can use [Remote Development extension pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) now. There is still an error. When I try to connect to a server, I get this error: "Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)". However, I can use VS code to connect the server.

**Comment by brianclinkenbeard** [comment]
FYI (since inclusion is being discussed and also some vscodium users seem to care about this) the remote development pack is at least currently [not FOSS](https://marketplace.visualstudio.com/items/ms-vscode-remote.vscode-remote-extensionpack/license).

**Comment by stripedpajamas** [comment]
@qlan3 unfortunately the server side code is not open source, so I don't know what conditions cause that error message. I would suspect it is because only Visual Studio Code is supported. Also, as @brianclinkenbeard mentioned, this feature if not freely licensed. This link as additional links to other related licenses to do with the Remote Dev extension, and they all restrict use to a "validly licensed copy of Microsoft Visual Studio Code". VSCodium (or a manual build of the `vscode` repo) do not fall into this category.

Will close this out for now, as I don't think there's anything further we can do until the licensing opens up or it's taken out of beta.

**Comment by tlrdstd** [comment]
I've bounced off this several times, so leaving a breadcrumb trail here for others. Combining this ticket, this [bug report](https://bugs.archlinux.org/task/62822), and [these docs](https://vscode-docs.readthedocs.io/en/stable/supporting/faq/#how-to-disable-telemetry-reporting), I did the following on my Mac, after installing `vscodium` via https://formulae.brew.sh/cask/vscodium:

```
vim /Applications/VSCodium.app/Contents/Resources/app/product.json
# edit extensionAllowedProposedApi to read:
"extensionAllowedProposedApi": ["ms-vscode.references-view", "ms-vsliveshare.vsliveshare", "ms-vscode-remote.vscode-remote-extensionpack", "ms-vscode-remote.remote-ssh"],
```

That gets me past the `command 'opensshremotes.*' not found` errors, but I still can't connect due to:

```
Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)
```

I filed https://github.com/microsoft/vscode-remote-release/issues/967 , and it appears to be a deliberate licensing choice by Microsoft to not allow use of the Remote Development extension pack with `vscodium` (as others have mentioned above).

No new information here, but wanted to put all the known details in one place.

**Comment by rawtaz** [comment]
FWIW, I questioned the limitation in the extension over at https://github.com/microsoft/vscode-remote-release/issues/1925 .

**Comment by tyoc213** [comment]
As version 1.55.2 I can't execute `ms-vscode-remote.remote-containers`

pinging @stripedpajamas

Do we have an ETA?

**Comment by bluppfisk** [comment]
following. Is the only way to get it to build it ourselves or is there something we can change in the configuration?

**Comment by firelizzard18** [comment]
Microsoft explicitly doesn't want you to use the remote development extensions with anything except official Microsoft VSCode. https://github.com/microsoft/vscode-remote-release/issues/967 quotes the license, which used to explicitly say you are only allowed to use these extensions with official VSCode. I don't read legalese, but unless something has changed, the remote extensions cannot be legally used with anything but VSCode (though the license may not actually hold up in court).

So unless Microsoft changes their mind, the only way to get these features is to re-implement them.

**Comment by skbeh** [comment]
If you meet "Connection error: Unauthorized client refused", just change `this._environmentService.isBuilt` in https://github.com/microsoft/vscode/blob/36bb6a6848574d883e0310885ebf2cf3269c48b9/src/vs/server/remoteExtensionHostAgentServer.ts#L418 to `false`.

**Comment by daiyam** [comment]
Interesting! It was added in October.

**Comment by daiyam** [comment]
@skbeh Yep, it's the way to go 😉

**Comment by daiyam** [comment]
I was able to patch the client and server to make it work with VSCodium. I don't know how to make it available to others...

**Comment by firelizzard18** [comment]
@AdvisedlyAlburn I think you're being a bit alarmist. Closed-source extensions are a minority and there isn't much evidence of a trend towards more closed source extensions from Microsoft. You can't blame Microsoft for the fact that Google made a closed-source GCP extension. The closed source remote extensions are obviously on Microsoft - my guess is that those are closed source because the remote editing capabilities gives VSCode a competitive edge and they want to retain that as long as possible. Pylance is probably about that too.

However, most of the popular VSCode extensions are open source and built around open source tools. Even if Microsoft did start close-sourcing their other extensions, the community could easily fork them. And since the tools they are built around are open source, the community could create their own extensions for those tools.

**Comment by krishnakumarg1984** [comment]
@daiyam Please do share the patching process.

**Comment by RDHB** [comment]
What is the way to make the extension work in vscodium?

**Comment by skbeh** [comment]
On this time, just change `153,2515` of `~/.vscode-server-oss/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/out/vs/server/remoteExtensionHostAgent.js`,
which is `!ye` to `true`.

**Comment by 0reo** [comment]
I had to edit ~/.vscode-server-oss/bin/f80445acd5a3dadef24aa209168452a3d97cc326/out/vs/server/node/server.main.js, and search for "client refused" string.  the variable for the if statement will likely be named differently but it's there.  I also had to first install it in vscode normal, and then copy the extension folders into the path for vscodium at %userprofile%/.vscode-oss/extensions

**Comment by IvanDL95** [comment]
Where is the  `~/.vscode-server-oss/bin` supposed to be? The `.vscode-server-oss` doesn't show up in my home directory. Both the `server.main.js` and `remoteExtensionHostAgent.js` doesn't show up in any of the home of vscodium for the flatpak, the snap nor the .deb package (as far as I found, for the .deb inside ~/.config  and for the flatpak in ~/.var/app/com.vscodium.codium/ and in the system folder in /var/lib/flatpak/app, didn't bother too much with the snap).

I can install the extension with the [docs workaround](https://github.com/VSCodium/vscodium/blob/master/DOCS.md), both in the .deb and the flatpak (plus the docker socket override for this one), but nothing happens, not even the "command 'opensshremotes.openConfigFile' not found" message shows up.

**Comment by IvanDL95** [comment]
So I fiddled a little more with bits from here and there between vscode, vscodium and flatpak vscodium and I've got the full steps to make it run. I know the flatpak is unnoficial but whatever, I'm gonna put the extra step and someone can link it from there. I guess making docker visible when using a .deb build comes "by default" as it has access to the same things as the user (assuming the **user in the docker group**).

1. To be able to install the extension I followed this [repo docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) to enable the microsoft marketplace.

2. I added [this config](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#proprietary-extensions) (again from the docs).

3. I came across with [issue #1034](https://github.com/VSCodium/vscodium/issues/1034), seems unrelated, but it says something about product.json that I'm not willing to check after going around poking the config, So I was left with this config `product.json`:

```
{
  "extensionsGallery": {
    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
    "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
    "itemUrl": "https://marketplace.visualstudio.com/items",
    "controlUrl": "",
    "recommendationsUrl": ""
  },
  "extensionAllowedProposedApi": [
    "GitHub.codespaces",
    "GitHub.copilot-nightly",
    "GitHub.copilot",
    "GitHub.vscode-pull-request-github-insiders",
    "GitHub.vscode-pull-request-github",
    "GitHub.remotehub",
    "GitHub.remotehub-insiders",
    "Microsoft.vscode-nmake-tools",
    "ms-dotnettools.dotnet-interactive-vscode",
    "ms-python.gather",
    "ms-python.python",
    "ms-toolsai.jupyter",
    "ms-toolsai.vscode-ai",
    "ms-toolsai.vscode-ai-remote",
    "ms-vscode-remote.remote-containers-nightly",
    "ms-vscode-remote.remote-containers",
    "ms-vscode-remote.remote-ssh-edit-nightly",
    "ms-vscode-remote.remote-ssh-edit",
    "ms-vscode-remote.remote-ssh-nightly",
    "ms-vscode-remote.remote-ssh",
    "ms-vscode-remote.remote-ssh-serverless",
    "ms-vscode-remote.remote-wsl",
    "ms-vscode-remote.remote-wsl-recommender",
    "ms-vscode-remote.vscode-remote-extensionpack-nightly",
    "ms-vscode-remote.vscode-remote-extensionpack",
    "ms-vscode.azure-account",
    "ms-vscode.azure-sphere-tools-ui",
    "ms-vscode.azure-sphere-tools",
    "ms-vscode.js-debug-nightly",
    "ms-vscode.js-debug",
    "ms-vscode.lsif-browser",
    "ms-vscode.vscode-selfhost-test-provider",
    "ms-vsliveshare.cloudenv-explorer",
    "ms-vsliveshare.cloudenv",
    "ms-vsliveshare.vsliveshare",
    "ms-vsonline.vsonline",
    "dbaeumer.vscode-eslint",
    "tanhakabir.rest-book",
    "VisualStudioExptTeam.vscodeintellicode",
    "VisualStudioExptTeam.vscodeintellicode-insiders",
    "VisualStudioExptTeam.vscodeintellicode-completions",
    "vscode.vscode-web-playground",
    "ms-azuretools.vscode-azureappservice"
  ],
  "extensionEnabledApiProposals": {
    "ms-dotnettools.dotnet-interactive-vscode": [
      "notebookConcatTextDocument",
      "notebookContentProvider",
      "notebookCellExecutionState",
      "notebookControllerKind",
      "notebookDebugOptions",
      "notebookDeprecated",
      "notebookEditor",
      "notebookEditorDecorationType",
      "notebookEditorEdit",
      "notebookLiveShare",
      "notebookMessaging",
      "notebookMime",
      "textDocumentNotebook"
    ],
    "ms-vscode.remote-repositories": [
      "contribRemoteHelp",
      "contribMenuBarHome",
      "contribViewsRemote",
      "contribViewsWelcome",
      "documentFiltersExclusive",
      "extensionRuntime",
      "fileSearchProvider",
      "quickPickSortByLabel",
      "workspaceTrust",
      "scmSelectedProvider",
      "scmValidation",
      "textSearchProvider",
      "timeline",
      "notebookEditor"
    ],
    "ms-vscode-remote.remote-ssh": [
      "resolvers",
      "terminalDataWriteEvent",
      "contribViewsRemote"
    ],
    "ms-vscode-remote.remote-containers": [
      "resolvers",
      "workspaceTrust",
      "terminalDimensions",
      "contribViewsRemote"
    ]
  }
}
```
In the flatpak, the file should be placed in `~/.var/app/com.vscodium.codium/config/VSCodium/` if using the default path

3.5. This is the extra step I was mentioning. It took me a lot of time as I came with a "drawing the rest of the owl moment" in [this issue in the vscode flatpak[(https://github.com/flathub/com.visualstudio.code/issues/203). I found the full explanation of how to do it [here](https://github.com/flathub/com.visualstudio.code/issues/189). It's for podman, but the steps are exaclty the same just that instead of `--host podman` it's `--host docker` and you have to also replace the Docker Compose Path.

4. What @0reo and @skbeh  were saying it's `~/.vscode-server-oss/bin` and confused me it was inside **the home folder of the root user inside the docker container**. So what it's actually the thing to do is:

  a. Go to the docker container
  b. Open `/root/.vscode-server-oss/bin/${randomHash}/out/vs/server/node/server.main.js` and search for client refused as @0reo said and search for the if with the negated variable (let's call it `!ye`) and replace `!ye` to `false` as @skbeh dixit.
  c. I had to copy the file code-server to code-server-oss inside of `/root/.vscode-server-oss/bin/${randomHash}/bin` because, for some reason I don't know. it was looking for the code-server-oss file instead. There will be an error sign and a log behind explicitly stating that it failed because that file doesn't exist if you don't.
  
5. Launch/relaunch VScodium if neccesary and see if the Remote Explorer is tab there and it shows the containers instead of a message to install docker and try to attach a codium window to it.

**Comment by reesericci** [comment]
wait, what? I'm working in a toolbox and that directory is not inside the toolbox, correct? I am very confused.
