### ISSUE TITLE
Debian/Ubuntu apt repository URL suspended or not configured

### ISSUE THREAD

**Issue by michael-sbarra** [VSCodium/vscodium#1991]
From the docs https://vscodium.com/#use-a-package-manager-deb-rpm-provided-by-vscodium-related-repos, the domain http://download.vscodium.com/deb is not valid. `apt update` fails with:

```log
E: Failed to fetch https://download.vscodium.com/debs/dists/vscodium/InRelease  403  Forbidden [IP: 143:244:49.180 443]
E: The repository 'https://download.vscodium.com/debs vscodium InRelease' is not signed.
```

The webpage shows bunny.net with `Domain suspended or not configured`.

**Comment by ChrisLauinger77** [comment]
Just wanted to report the same

**Comment by OIRNOIR** [comment]
This problem also affects rpm-based distros like Fedora, which also use the same `download.vscodium.com` domain.
DNF refuses to connect because the SSL certificate served by the suspended domain thing is invalid.

```
download.vscodium.com                                                         0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'gitlab.com_paulcarroty_vscodium_repo':
  - Curl error (60): SSL peer certificate or SSH remote key was not OK for https://download.vscodium.com/rpms/repodata/repomd.xml [SSL: no alternative certificate subject name matches target host name 'download.vscodium.com']
Error: Failed to download metadata for repo 'gitlab.com_paulcarroty_vscodium_repo': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: gitlab.com_paulcarroty_vscodium_repo
```

**Comment by bvobart** [comment]
I'm experiencing the same problem in Nobara and found [this issue](https://github.com/VSCodium/vscodium/issues/1050) from 2 years ago where it is mentioned that the Gitlab mirror can be used as a workaround until the SSL and CDN issues are fixed.

If you run Fedora, Nobara or some other RPM-based distro, run this command to update your VSCodium repository URL to the Gitlab mirror:

```
sudo sed -i 's,baseurl=.*,baseurl=https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms,' /etc/yum.repos.d/vscodium.repo
```

Then run `sudo dnf update` and you should see DNF successfully be able to update the VSCodium RPM repository.

Once this issue is fixed, then run the following command to switch back to the official download.vscodium.com mirror:

```
sudo sed -i 's,baseurl=.*,baseurl=https://download.vscodium.com/rpms/,' /etc/yum.repos.d/vscodium.repo
```

**Comment by ChrisLauinger77** [comment]
It is working fine again - think can be closed ...

**Comment by daiyam** [comment]
I would avoid to use directly `paulcarroty.gitlab.io` since there are limits (https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits)

**Comment by bvobart** [comment]
Alright, thanks for mentioning it, @daiyam, I'll switch back to the `download.vscodium.com` mirror. The Gitlab mirror was very useful in allowing my system to fully update though :relaxed:
