### ISSUE TITLE
404 - [1.96.2.24355] remote host release file not found

### ISSUE THREAD

**Issue by orctom** [VSCodium/vscodium#2169]
Upgraded to this release, and failed to setup remote connection automatically.
Then I checked this link: https://github.com/VSCodium/vscodium/releases/download/1.96.2.24355/vscodium-reh-linux-x64-1.96.2.24355.tar.gz 
It says NOT FOUND
![image](https://github.com/user-attachments/assets/e47bbde3-d27c-40d9-b909-74a6c3060fc2)

And found the number of assets of this release is 32, previous was 154
![image](https://github.com/user-attachments/assets/3661a54c-17de-49b5-a5c5-9ccff4f03b8b)

**Comment by daiyam** [comment]
The Linux workflow failed because of a new error, fixed in #2168
The Windows workflow failed because there is a manual step (to authorize the signing requests). It did timeout (3h).
The table is generated at the beginning, way before any artifact is ready. It there so it's easier to get the right artifact.

I didn't get any notifications for the failures and the new release...

They should go up soon.

**Comment by daiyam** [comment]
All the artifacts are available.
