### ISSUE TITLE
Building process

### ISSUE THREAD

**Issue by desk7** [VSCodium/vscodium#217]
Just some questions about the building process:
- Changing the default `product.json` file in VSCode with yours will give the same result?
- even in VSCodium building process additional files are downloaded?
- Can the extension marketplace be used? Are No tracking data sent?

**Comment by stripedpajamas** [comment]
For general questions (and further discussion), please use the gitter.im link in the readme rather than opening an issue.

> Changing the default product.json file in VSCode with yours will give the same result?
There are more steps to producing the VSCodium binaries than changing the values in `product.json`. Refer [here](https://github.com/VSCodium/vscodium#how-are-the-vscodium-binaries-built).

> even in VSCodium building process additional files are downloaded?
Yes, as mentioned [here](https://github.com/VSCodium/vscodium#why-does-this-exist), the build process downloads additional files and they are listed.

> Can the extension marketplace be used? Are No tracking data sent?
I don't know if anyone has done any serious digging into what tracking data is sent by the extension marketplace, but at the very least, search terms and installed extensions would be visible to MS. We keep the extension marketplace in VSCodium because we think it's an important part of the IDE and there isn't an open source replacement out there that we know of.

**Comment by desk7** [comment]
Thanks for answer. Just some notes:
- in the readme you say "Microsoft's build process does download additional files." So, for me, it is not obvious that the build process you set up does the same.
- An alternative to marketplace could be manually downloading extension and install offline.
- Do you know if, blocking internet connection with a firewall, VSCode still connects to internet through Windows 10 services?
