### ISSUE TITLE
Is there any difference if we disable telemetry in VSCode?

### ISSUE THREAD

**Issue by divyanshu013** [VSCodium/vscodium#219]
Hi, I was curious on what's the difference between vscodium and vscode if we just disable telemetry as mentioned in the [faq](https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting).

Thanks!

**Comment by stripedpajamas** [comment]
Regarding telemetry, it's pretty much the same. Visual Studio Code will still send some telemetry on first start and will send telemetry that you disabled telemetry, so that is one difference.

Mostly though, the difference is the license. Some people don't like the Visual Studio Code license and prefer the built-from-source MIT license.

**Comment by stripedpajamas** [comment]
For general questions, consider using the gitter.im link in the readme rather than opening an issue.
