### ISSUE TITLE
Differences to Code-OSS?

### ISSUE THREAD

**Issue by polarathene** [VSCodium/vscodium#267]
I've been using Code-OSS packaged in Arch Linux(Not the Flatpak/Flathub version I've seen around/mentioned, though I assume that's the same in a flatpak deliverable).

Recently heard of VSCodium, but it's not clear how these two compare? They seem to be doing the same thing? Are there some subtle differences? I've only seen comparisons of each to MS VSCode.

**Comment by stripedpajamas** [comment]
They are very similar. Code-OSS is what you get when you build vscode from source. VSCodium is essentially just a build script that automatically builds from source when MS cuts a new release and then uploads the binaries here to GitHub. In that sense it is mainly to save time. 

Additionally, VSCodium turns off telemetry in the build process, and rewrites some of the deeply nested telemetry URLs to go nowhere in case something in the codebase tries to send info back to MS. So that is a small difference that a standard build of Code-OSS would not have unless it was done manually. 

I'm not sure how the packaging was done to get Code-OSS into Arch, so it's possible there are other differences with the Arch version specifically. 

The README of this repo goes into more detail. For non-bugs and general questions, please use the gitter.im link in the repo.

**Comment by polarathene** [comment]
> In that sense it is mainly to save time.

That's what the Linux packages of Code - OSS took care of afaik, I also thought they did similar changes to what VSCodium does, but I appear to be mistaken.

I can see how it'd be of benefit on other platforms where a package was lacking. Now that my misunderstanding between the two is cleared up, I'll switch over to VSCodium, thanks.

> The README of this repo goes into more detail. 

I was under the understanding that Code-OSS wasn't just a build of the vscode repo. I had thought it also removed telemetry(or at least disabled by default), that doesn't appear to be the case with the Arch package(it was enabled in my settings).

Since I thought it was different, similar to VSCodium, I didn't think the README explanation was actually referring to Code-OSS (the similarly named flatpak variant added to that confusion).

> For non-bugs and general questions, please use the gitter.im link in the repo.

That "chat on gitter" badge was buried in the noise of the others. Perhaps adding a section about where to direct questions could be added to the README to avoid this in future? I did go over the README and searched existing issues briefly before creating an issue.

Alternatively, having a template for questions to go along with the bug report one(which is the only one), could have the template contents inform the user that questions should not be raised here, but instead on gitter?

The question seemed appropriate at the time as an issue since others would be able to find it. Cheers for the response :)
