### ISSUE TITLE
Remove "VS" from name?

### ISSUE THREAD

**Issue by jaredreich** [VSCodium/vscodium#28]
In regards to avoiding trademark issues, shouldn't the use of "VS" and "Visual Studio" be removed since that's the name of the Microsoft suite of products? Perhaps this should be named "Codium"? Thoughts?

**Comment by stripedpajamas** [comment]
Any references to "Visual Studio" should be removed (are there any?), but I like keeping the VS part of VSCodium, because it matches with the idea of Chrome/Chromium. "vscode" is MIT licensed, whereas "Visual Studio Code" is not. So iterating on the MIT licensed "vscode" into "VSCodium" seems kosher to me. 

Will leave open for a couple of days to allow further discussion

**Comment by jaredreich** [comment]
Ok sounds like you've already done your research on this. Just wanted to ask!

**Comment by Jorgeelalto** [comment]
For me it is OK. Originally it comes from Visual Studio but since the name of the project is vscodium and it does not come explicitly from Visual Studio Codium, I don't really think there should be any problem. We can even make up our own meaning of VS...

**Comment by paulcarroty** [comment]
It is completely legal to use the `Visual Studio` subbrand?

It's seems like deleting `Adobe` from `Adobe Photoshop Elements` and use only `Photoshop Elements`. I'm not lawyer, but stealing the part of original brand is dirty.

**Comment by stripedpajamas** [comment]
We aren't using "Visual Studio" anywhere. We are using the letters "vs". There exists a open source project called "vscode" and there exists a product called "Visual Studio Code". 

@paulcarroty in my opinion your example does not line up with what is happening here. Perhaps a more fitting example: Adobe has an open source project called "brackets". If we were to find something awry with the way it is built and Adobe declined to accept PRs to remedy the situation, we might create "bracketium" which builds "brackets" a specific way but has a name that users can use to distinguish between the two.

**Comment by dzmitry-lahoda** [comment]
Renaming to codium would make me happy.

When I type `code` and get into editor - cool.
When I type `vscodium` - I am unhappy.
Making option in installer to name `exe` as `code` would make me very happy.

**Comment by bittner** [comment]
I agree with @dzmitry-lahoda. It may be just a matter of getting used to it, but ...

What would be the deal if we followed the same idea as the non-free distribution?
`codium` instead of `code` (for the binary's name only) - that's much easier to get used to.

Any thoughts?

P.S.: I don't think suggesting an alias (as mentioned in https://github.com/VSCodium/vscodium/issues/36#issuecomment-487593841) can remedy the situation for transitioners.
P.P.S.: Can we reopen this issue?
