### ISSUE TITLE
Live Share's sign in does not work

### ISSUE THREAD

**Issue by lodi-g** [VSCodium/vscodium#320]
**Describe the bug**
When signing in either through Microsoft or GitHub with Live Share, the connection process does not go through.
From Microsoft: `AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'a3037261-2c94-4a2e-b53f-090f6cdd712a'.`
From GitHub: `Unsupported redirection domain.`

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'Live Share' tab
2. Click on 'Start Collaboration Session'
3. Click on 'Sign in with Microsoft'
4. Sign in with the browser
5. See error in the browser (VSCodium hangs on 'signing in...')

**Expected behavior**
I expected to sign in and use Live Share.

**Screenshots**
![2020-02-02T19:40:12+01:00-96550](https://user-images.githubusercontent.com/4528943/73613330-5f330900-45ec-11ea-91ef-ca17b766cfe9.png)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Architecture: Linux laptop 5.4.15-arch1-1 #1 SMP PREEMPT Sun, 26 Jan 2020 09:48:50 +0000 x86_64 GNU/Linux
 - Version: 1.41.1

**Additional context**
N/A

**Comment by forward2k** [comment]
Temporary workaround:
Copy the link from VSCodium login, replace vscodium: with vscode: 
If you still have a redirect error, copy the user code from the address bar and use it with the sign in with user code option (via Alt+P) on vscodium

**Comment by stripedpajamas** [comment]
@lodi-g I think @forward2k 's temporary workaround is as good as we can get here -- since the extension/website assumes a "vscode:" protocol, manual intervention is needed to tell it about VSCodium. Will close this out for now.

**Comment by hoshsadiq** [comment]
Hi this doesn't seem to work for me, nor am I unable to find the option where I can put in the user code. Is it possible to elaborate?

**Comment by hoshsadiq** [comment]
So just to elaborate on my part, when I change to `vscodium:` with `vscode:`, it asks for `xdg-open` to launch VSCodium, which I allow, but then allows as OP mentioned, it stays on `Signing In...`. For some reason it doesn't seem to receive the call from the browser.

**Comment by hoshsadiq** [comment]
So to add more, I'm able to get VSCodium to bring up below screen, but still nothing.

![image](https://user-images.githubusercontent.com/600045/80414523-14621e00-88c9-11ea-9893-4538c665f48c.png)

**Comment by purifyyourhome** [comment]
> So just to elaborate on my part, when I change to `vscodium:` with `vscode:`, it asks for `xdg-open` to launch VSCodium, which I allow, but then allows as OP mentioned, it stays on `Signing In...`. For some reason it doesn't seem to receive the call from the browser.

same here on Mac OS X 10.13
<img width="1552" alt="Screen Shot 2020-05-03 at 3 52 33 PM" src="https://user-images.githubusercontent.com/44551716/80924291-1f4c0100-8d56-11ea-8e2a-3f9eadf3f58d.png">

**Comment by hoshsadiq** [comment]
@stripedpajamas could we please reopen this and possibly find a solution?

**Comment by Vrishtrix** [comment]
**Try logging in with your user code**

Step 1: Go to this [https://insiders.liveshare.vsengsaas.visualstudio.com/auth/login](url)

Step 2: Login with microsoft account and copy the code.

Step 3: Open command palette in VSCodium and type _user code_. In the popup box, just enter the code.

**This sould work in most cases**

**Comment by nicosierra** [comment]
One additional step to the comment from @Vrishtrix. 
To copy the code: click first on "Having trouble? Click here for user code directions", 
(I was actually copying it from the url 🤦 )
The whole instructions are in: https://docs.microsoft.com/en-us/visualstudio/liveshare/use/vscode#sign-in-using-a-user-code

**Comment by GitMensch** [comment]
reference-link for a somedayTM own remote option: #266

**Comment by bendem** [comment]
Anyone got a clue about github login? All the comments here assume microsoft login from what I can tell.

**Comment by bendem** [comment]
Alright, workaround provided in https://github.com/MicrosoftDocs/live-share/issues/3218 works:
* go to https://insiders.liveshare.vsengsaas.visualstudio.com/auth/login and sign in with github
* click the user code link and copy the user code
* use the code in vscodium under the command `Live Share: Sign In With User Code`

**Comment by GitMensch** [comment]
That workaround is listed here already: https://github.com/VSCodium/vscodium/issues/320#issuecomment-639345453 :-)

**Comment by nclsbayona** [comment]
Hi, I still can login with my GitHub account, can I have some help please?

**Comment by milofultz** [comment]
None of the mentioned workarounds here get me to activation of Liveshare within VSCodium. I get to this screen and it sends a request, but VSCodium doesn't recognize anything occurring.

<img width="572" alt="Screen Shot 2021-01-26 at 9 50 27 AM" src="https://user-images.githubusercontent.com/65684361/105883730-05c1a800-5fbc-11eb-8f28-37b51e4e2e4e.png">

This is after changing the `vscodium` to `vscode` in the URL.

I also tried signing in with the user code, but VSCodium doesn't seem to respond to the code being submitted.

I'm using OSX 10.14.6 (18G7016) on a MacBook Pro (Retina, 15-inch, Mid 2015).

Appreciate your help, thank you

**Comment by hazarek** [comment]
If you are going to connect to microsoft services with a microsoft account, why are you using VScodium. Doesn't Live Share send data over the network?

**Comment by milofultz** [comment]
I need to use Liveshare for a project, but this is an edge case for me so I'm hoping to not have both installed at once. If i have to use VSCode instead it's no problem, but would prefer the one without telemetry the rest of the time.

**Comment by Avaq** [comment]
It seems that since this change (https://github.com/MicrosoftDocs/live-share/issues/4128), the workarounds described here are no longer relevant, as the `Live Share: Sign In With User Code` option appears to have been removed. I found a new work-around:

1. From VSCode, click sign in with Github
2. Follow the login flow until the browser tries to open VSCode, reject that request
3. Copy the authentication token and paste it into an editor (the opened VSCode is fine)
4. From VSCodium, click sign in with GitHub
5. In the browser page that opens, find the `state` parameter in the URL, copy its value, you can close this page now
6. Replace the `state` parameter with this value in the authentication token you've acquired in step 3
7. Replace "vscode://" with "vscodium://" in the authentication token
8. In VSCodium click on the "Signing in with GitHub..." section in the status bar, and paste your modified token

The first time I tried this it failed, but I think the token is very short-lived. I tried it again by going through the steps much faster and the second time it worked.

**Comment by GitMensch** [comment]
@Avaq Do you really suggest to have VSCode installed next to VSCodium (possibly only for using Live Share)?

If anyone has a issue with that I _guess_ that disabling the new "nativeAuth" as noted in https://github.com/MicrosoftDocs/live-share/issues/4130#issuecomment-786898008 should work to get to the old status.

**Comment by WJ714** [comment]
> It seems that since this change ([MicrosoftDocs/live-share#4128](https://github.com/MicrosoftDocs/live-share/issues/4128)), the workarounds described here are no longer relevant, as the `Live Share: Sign In With User Code` option appears to have been removed. I found a new workaround:
> 
> 1. From VSCode, click sign in with Github
> 2. Follow the login flow until the browser tries to open VSCode, reject that request
> 3. Copy the authentication token and paste it into an editor (the opened VSCode is fine)
> 4. From VSCodium, click sign in with GitHub
> 5. In the browser page that opens, find the `state` parameter in the URL, copy its value, you can close this page now
> 6. Replace the `state` parameter with this value in the authentication token you've acquired in step 3
> 7. Replace "vscode://" with "vscodium://" in the authentication token
> 8. In VSCodium click on the "Signing in with GitHub..." section in the status bar, and paste your modified token
> 
> The first time I tried this it failed, but I think the token is very short-lived. I tried it again by going through the steps much faster and the second time it worked.

works for me. Big thanks!

**Comment by Avaq** [comment]
> Do you really suggest to have VSCode installed next to VSCodium (possibly only for using Live Share)? -- @GitMensch 

That's a necessity for this approach, yes. I mainly just shared the approach so that someone else might be able to automate it or something, or build on it.

> works for me. Big thanks! -- @WJ714 

I only found out later that I keep having to repeat these steps every few days, because the login session seems to expire. That does make it a little less attractive.

**Comment by jonstump** [comment]
I've attempted multiple solutions listed here and can no longer use codium with live share. It used to work a while back, and sadly I don't know what version it stopped with. Basically, mine always asks me if I want to sign in with GitHub or Microsoft account and there's no option to use the code to sign in with. When I attempt that I get a 401 unathorized (even though Codium is logged into Github).

 Literally, the only reason I currently use VSCode/Codium is for pair programming so it's kind of a bummer MS seemed to have broke this with some new auth implementation. Also I assume it'll be annoying if I did get the code to work because they seem to have us relog back in every so often now for live share.

**Comment by toddewilliams** [comment]
Microsoft isn't going to address this bug because Live Share is a Microsoft product and you're forbidden from using it in VSCodium (or anything that isn't Microsoft VS Code).

The [Live Share license agreement ](https://marketplace.visualstudio.com/items/MS-vsliveshare.vsliveshare/license) specifically states that it can only be used in Microsoft VS Code (section 1) and that you're not allowed to work around this restriction by trying to mimic VS Code (section 5).

Additionally, you're not allowed to install ANYTHING from the extension marketplace into a non-Microsoft product according to that site's [terms of use](https://cdn.vsassets.io/v/M146_20190123.39/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf). See section 1b.

VSCodium is basically not at all welcome here and Microsoft should just tell you what I just did and close this bug as "WONT FIX".

That said, you have a better option anyway. 

Go install [CodeTogether](http://www.codetogether.com) from the website or the [Open VSX Marketplace](https://open-vsx.org/extension/genuitecllc/codetogether) and you'll be able to live share from VSCodium or any other IDE based on the Code source (including VS Code). And you'll be able to share between Eclipse-based and IntelliJ-based IDEs too. You'll have freedom of choice to use any of your favorite IDEs and still live share your development sessions between them all. And yes, there is a totally zero cost plan because we all love free.

Disclaimer: CodeTogether is a product of Genuitec and I not only work there, I co-founded it over 20 years ago to build professional tools for other software developers. However, I'm posting here simply because y'all need to know the truth about why you'll never see Microsoft support VSCodium and to welcome all y'all to our freedom of choice alternative.

**Comment by GitMensch** [comment]
> If anyone has a issue with that I _guess_ that disabling the new "nativeAuth" as noted in [MicrosoftDocs/live-share#4130 (comment)](https://github.com/MicrosoftDocs/live-share/issues/4130#issuecomment-786898008) should work to get to the old status.

Just out of interest: has someone tested that (disabling native-auth, then using the "old" approach from above)?

What is really missing for me is a solution which works completely along the Editor, something like CodeTogether with the server-side being on the client that starts the session... @toddewilliams CodeTogether will get interesting for me if I can use an "onPremise"-Version without the enterprise tools (just a gateway that I can manually configure in the IDE).

**Comment by toddewilliams** [comment]
> @toddewilliams CodeTogether will get interesting for me if I can use an "onPremise"-Version without the enterprise tools (just a gateway that I can manually configure in the IDE).

@GitMensch Well, I'm not exactly sure what you mean, but I'll explain what we have and you can determine the fit.

Our primary service is SaaS and that can be accessed completely anonymously if desired. Our servers are in the US and Europe to optimize for performance based on locality. On the client you just have to install the extension and ["Host new session"](https://www.codetogether.com/docs/three-steps-to-pair-programming-vs-code/) and you get a URL to share. Others can join from a browser or their IDE of choice. 

Or you can [create a team](https://www.codetogether.com/teams/) and you'll get live sharing invites in your IDE as someone in your team starts sharing.

Or for the ultimate in control and security you can install our server [on-premises](https://www.codetogether.com/on-premises/) and use your SSO provider for authentication while keeping everything behind your firewell.

And no matter which you choose, everything is [end-to-end encrypted](https://www.codetogether.com/download/security/) and our servers don't have the keys so we couldn't decrypt if we had to.

I believe what you're suggesting, "with the server on the client" wouldn't scale well due to bandwidth, processing, and routing demands as we allow up to 32 developers in our sessions. This is only possible due to the size and locality of the servers as well as the edge network we use.

If you (or anyone) has questions, just hit me up on twitter with the same handle. DMs are fine if you want to keep it private as well.

**Comment by daiyam** [comment]
I've added the wiki page: https://github.com/VSCodium/vscodium/wiki/Extensions-Compatibility

**Comment by GitMensch** [comment]
Thanks for taking care. Can someone please try to list alternatives there?

**Comment by toddewilliams** [comment]
> Thanks for taking care. Can someone please try to list alternatives there?

I was thinking the same thing and would greatly appreciate some alternatives on the Wiki. Here's one entry with links if someone with commit rights would add it please.

([Genuitec's](https://genuitec.com)) [CodeTogether](https://codetogether.com) extension is a complete replacement for Live Share and also enables cross-IDE live share between IDEs based on Code OSS (like VSCodium), Eclipse, and IntelliJ, not just IDEs created by Microsoft.

CodeTogether is available on the [open-vsx ](https://open-vsx.org/) marketplace [here](https://open-vsx.org/extension/genuitecllc/codetogether).

**Comment by daiyam** [comment]
Should we "promote" any alternatives, even proprietary ones? Or just focus on open source alternatives?

**Comment by toddewilliams** [comment]
> Should we "promote" any alternatives, even proprietary ones? Or just focus on open source alternatives?

Could you simply list all of the alternatives and let the viewers decide what's important to them? There are many cross-products between OSS, Free, Commercial, and Paid and everyone has different criteria they use to judge what they use. 

In CodeTogether's case, it's a commercial product but there is a [Free plan](https://www.codetogether.com/pricing/) that you can use forever. But there are also a variety of paid plans because I have brilliant software developers that I enjoy paying to do great work and they appreciate being paid to do what they love to do.

**Comment by acoolstraw** [comment]
todd shut the fuck up
