### ISSUE TITLE
corruption notification doesn't have a "Don't show again button"

### ISSUE THREAD

**Issue by vaaski** [VSCodium/vscodium#326]
**Describe the bug**
I'm using [this](https://github.com/be5invis/vscode-custom-css) extension to inject custom css and an expected side effect is that vscode complains about the installation being corrupt. Now with normal vscode there's an option to never show the notification again like seen here:
![image](https://user-images.githubusercontent.com/17879327/74165878-0552c480-4c26-11ea-9782-15c319750dc9.png)
That option isn't there when I use vscodium, like seen here:
![image](https://user-images.githubusercontent.com/17879327/74165958-24e9ed00-4c26-11ea-8a5d-3b5e299475a1.png)

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install the [custom css extension](https://github.com/be5invis/vscode-custom-css)
2. From the command palette run `Enable Custom CSS and JS` and reload vscodium
3. Shortly after loading there should be a notification saying that the installation is corrupt, which doesn't have an option to not show again

**Expected behavior**
I expect to have the option to not see the notification again, ever.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Architecture: x64
 - Version: 1.42.0 User

**Comment by stripedpajamas** [comment]
It looks like MS checks for a URL in the "product service"; if it finds the URL, it gives you the option to not show the message again; otherwise it does not give the option: https://github.com/microsoft/vscode/blob/7f035b4be73a7ce9ceafb2128c066b717eafaf87/src/vs/workbench/services/integrity/node/integrityService.ts#L91-L116

I see in the Visual Studio Code's product.json file, there is such a property:

```json
	"checksumFailMoreInfoUrl": "https://go.microsoft.com/fwlink/?LinkId=828886",
```

I believe the fix for this issue will be to add a similar property to our own product.json file at build time. It's probably fine to even use their URL.
