### ISSUE TITLE
1.42.0 on macOS does not run "This software needs to be updated"

### ISSUE THREAD

**Issue by desrod** [VSCodium/vscodium#327]
As in the attached screenshot, it looks like the developer account might have expired or the wrong SDK is being used to package it. The macOS version of codium doesn't run at all, displaying the error dialog in the attached image: 

<img width="532" alt="Screen Shot 2020-02-11 at 2 50 05 PM" src="https://user-images.githubusercontent.com/5942125/74273174-ffb8b580-4cdd-11ea-9c62-beede1743387.png">

**Comment by stripedpajamas** [comment]
@desrod it should be that you can context-click the App and then hit "Open" while pressing `alt/option` on the keyboard. After doing this once it should open normally in the future.

This is due to the app not being notarized and the developer signing key being relatively new compared to Microsoft's signing key. We have an open issue to get the notarization sorted out (#324)
