### ISSUE TITLE
Command-line installation of extension fails

### ISSUE THREAD

**Issue by PatrickMassot** [VSCodium/vscodium#332]
**Describe the bug**
Running `codium --install-extension ...` doesn't seem to do anything, it launches VScodium without installing anything.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Download codium at https://github.com/VSCodium/vscodium/releases/download/1.42.1/VSCodium-linux-x64-1.42.1.tar.gz, uncompress
2. run `./codium --install-extension jroesch.lean`
3. See no extension being installed

**Expected behavior**
VScodium should install the extension and quit.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Architecture x64
 - Version 1.42.1

**Comment by stripedpajamas** [comment]
It seems to be working for me (on Mac):

![image](https://user-images.githubusercontent.com/2707340/74617530-6ecd4a00-50e2-11ea-9ad0-dc76c9d8b9fd.png)

And I confirmed it shows up as an installed extension when I open VSCodium afterwards. So it may be Linux-specific. I will try to reproduce this on a Linux machine when I get some time. How did you go about installing your version of VSCodium?

**Comment by PatrickMassot** [comment]
As I wrote in my initial message, I simply downloaded the tar.gz file from the GitHub release page. This is crucial because the goal is to to make a zip file containing Codium (in "portable mode"), the extension and some other software all in one folder for easy distribution.

**Comment by 0wk** [comment]
I have discovered the problem - the executable file "codium" in the root directory of the program does not support the command line interface, it can only invoke the GUI of the program.
The "codium" in the "bin" sub-directory of the program's root directory is the real program can be used in command Line interface. If you want to execute any command, you must use this instead of the "codium" in the root directory.

 Expalnation: The Visual Studio Code is an electron based program, if it want to receive any argument from command line, a special argument must be passed in first, and if you look at the Command Line Interface "codium.bat" for Windows platform, you will discover this: 
> "%~dp0..\VSCodium.exe" "%~dp0..\resources\app\out\cli.js" %*
The "%~dp0..\resources\app\out\cli.js" is the special argument I mentioned, which implements the command line interface.

**Comment by daiyam** [comment]
Yep, `bin/codium` is the main entry of the program. Not sure how to resolve the issue...

**Comment by daiyam** [comment]
@PatrickMassot You should use the command `./bin/codium --install-extension jroesch.lean`.

**Comment by PatrickMassot** [comment]
I can confirm this works here. Thanks for investigating! I guess that properly fixing this issue would be difficult so you can only document this quirk somewhere in the installation instructions (next to the place you should really warn people that the `tar.gz` archive contains no root folder and will dump dozens of files and folder wherever you unpack it, which is super annoying).
