### ISSUE TITLE
Gruvbox/Gruvbox Material color scheme color not consistent.

### ISSUE THREAD

**Issue by aasutossh** [VSCodium/vscodium#338]
**Describe the bug**
Color is different at different places, please see https://github.com/gruvbox-material/vscode/issues/11.

It's the same with vscode. Other schemes work fine.

It could be an issue with Nvidia driver,
I just tried to see if it exists in other platforms, I tested it on windows with intel graphics, it didn't exist.
I am using pop os with Nvidia graphics driver version 440.44 if it matters.

**Comment by stripedpajamas** [comment]
Ok -- if it happens in VSCode (as you mentioned in https://github.com/gruvbox-material/vscode/issues/11) then there's definitely nothing we can do here in VSCodium (since we are only building the vscode sources).

I'll close this out with the recommendation that you open an issue with vscode directly https://github.com/microsoft/vscode/issues

**Comment by aasutossh** [comment]
I was gonna do that, but didn't know that vscode was available on github.
Thanks.
