### ISSUE TITLE
Question, regarding marketplace extensions posiblity to send telemetry data

### ISSUE THREAD

**Issue by wolfiton** [VSCodium/vscodium#340]
Hi VSCodium Team,

In my article here https://dev.to/wolfiton/vscodium-the-open-source-version-of-vscode-without-telemetry-4dn0.

I received a question in the comment section, regarding if the marketplace extensions can send telemetry data even though you disabled VSCodium telemetry option(The VSCodium disabled telemetry in VSCodium)  ?

Thanks in advance

**Comment by stripedpajamas** [comment]
Hi @wolfiton -- first of all thanks again for writing the article. Second, questions like this one are best sent on in our Gitter chat (gitter.im/VSCodium/lobby) so that the issues don't get too clogged up. 

To answer your question: yes! Extensions are 3rd party code and each must be evaluated for telemetry on its own. Many MS-built extensions are programmed to send telemetry and it isn't clear whether or not those extensions honor VSCode/VSCodium's telemetry settings. 

Additionally, the marketplace itself should be considered a 3rd party API (owned by Microsoft), so any searches / installations using the marketplace (including from within VSCodium) are most likely being logged and aggregated by the API owner.

For more info there is a small section on our Docs page about it and other parts of VSCodium that "use online services": https://github.com/VSCodium/vscodium/blob/master/DOCS.md

Cheers

**Comment by wolfiton** [comment]
Thanks for the reply @stripedpajamas, 
Can I quote your comment in the article?
Do you give me permission to add your response to my article as an update?

**Comment by stripedpajamas** [comment]
Yes, you can quote me.

**Comment by wolfiton** [comment]
Thanks for the permission @stripedpajamas , I updated the post with your explanation.
