### ISSUE TITLE
VSCodium is not identifying Source Control provider

### ISSUE THREAD

**Issue by vncastanheira** [VSCodium/vscodium#343]
**Describe the bug**
VSCodium does not identify Git as source provider.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open a folder containing a project that is using Git.

**Expected behavior**
VSCodium should be able to identify the source control the project is using.

**Screenshots**
![Code_eU4GhWHBvF](https://user-images.githubusercontent.com/1210284/75103810-eddce980-55de-11ea-81b1-ac0bd760cc85.jpg)

**Desktop:**
 - OS: Windows 10 1909
 - Architecture x64
 - Version 1.42.1

**Comment by bloron** [comment]
Same issue for me.
- Version 1.42.1

**Comment by LemosLucas** [comment]
It seems a more generic problem for me. VS Code seems to be stuck on some process during start-up. Even with all extensions disabled, the CPU consumption is very high until VS Code is closed. Also, I can feel that some features are not working as expected: 
 - I cannot preview markdown files (nothing happens when pressing CTRL+SHIFT+V or CTRL+SHIFT+P and looking for markdown preview)
 - There is no integration with git. The folder is not recognized as a git repository (git bash works fine)

VS Code version: VSCodium 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-14T10:21:44.789Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>

Extensions: none

**Comment by ericmoon** [comment]
I had a similar issue (probably the same) that coincided with windows defender quarantining a false postive trojan -> #331 

Rectified by having windows defender ignore that instance and re-download/install
