### ISSUE TITLE
1.44.0 release even though there's no 1.44.0 tag on Github

### ISSUE THREAD

**Issue by nulldowntime** [VSCodium/vscodium#351]
**Describe the bug**
VSCodium updated itself to 1.44.0 even though the latest tag is 1.43.0. There are mixed versions of assets under 1.43.0 tag, both 1.43.0 and 1.44.0.

**Please confirm that this problem is VSCodium-specific**
Can't verify, I don't use Microsoft's Visual Studio Code.

**Please confirm that the issue/resolution isn't already documented**
- irrelevant, I think

**To Reproduce**
1. Allow VSCodium to update itself as of now.

**Expected behavior**
Latest version matching the latest release on Github, 1.43.0.

**Screenshots**

![image](https://user-images.githubusercontent.com/6119357/76316262-962ac780-62da-11ea-8779-f4df3cd311d1.png)

![image](https://user-images.githubusercontent.com/6119357/76316337-b9557700-62da-11ea-8afd-3b5f6b35aa96.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Architecture: x64
 - Version: good question

**Additional context**
n/a

**Comment by GammaGames** [comment]
Is the latest release based on insiders? I got the insiders release notes

**Comment by stripedpajamas** [comment]
I'm not sure what happened, but I think it's more a confusion on the vscode side of things -- I only see up to 1.43.0 tagged https://github.com/microsoft/vscode/tags

During our build, we checkout the latest tag and use that as our version. Maybe yesterday they had a 1.44.0 tag but have since deleted it? I'm not sure how we ended up in this mess. When they add the 1.44.0 tag we will rebuild and cut a "new" release. 

@GammaGames AFAIK insiders releases aren't tagged, and we always check out the latest tag before building... so it _shouldn't_ be insiders unless something upstream is messed up.

Will close this and wait for something to happen upstream as I don't think there are any corrective actions we can take here that wouldn't result in problems with existing users.

**Comment by hrj** [comment]
This was very confusing (release title and linux package is 1.43, but the version inside the about dialog and release notes were for 1.44).

When cutting a build may I suggest not using the latest tag automatically, but to have it hard coded in a file in this repo?

**Comment by tyrak** [comment]
This was probably due an upstream screw up: microsoft/vscode#92403. They force updated the `1.43.0` tag in their repo so everything should build fine now.

**Comment by scottfurry** [comment]
However, this issue and #352 are both, IMHO, valid descriptions of an existing issue.
There are 1.44 and 1.43 assets shown on the [release page](https://github.com/VSCodium/vscodium/releases/tag/1.43.0). Version string in about dialog still shows 1.44.0.

Upstream seems to have gotten their act together with a "1.43.0" release. Version string seems correct in that about dialog.
