### ISSUE TITLE
No deb&rpm packages in v1.43 artifacts

### ISSUE THREAD

**Issue by paulcarroty** [VSCodium/vscodium#355]
https://github.com/VSCodium/vscodium/releases/tag/1.43.0

**Comment by BasRoufs** [comment]
Cannot update anymore VS Codium - probably because of this issue. 
Distro: Kubuntu 18.04 LTS.

Feedback at the console:

bas@Viaconsensus-iter:~$ sudo apt update
Hit:1 http://nl.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://ppa.launchpad.net/bluetooth/bluez/ubuntu bionic InRelease                                                                      
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]                                                                                                                    
Hit:4 http://nl.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                                                             
Hit:5 https://updates.signal.org/desktop/apt xenial InRelease                                                                                                                                  
Hit:6 http://ppa.launchpad.net/gezakovacs/ppa/ubuntu bionic InRelease                                                                                                                          
Hit:7 http://nl.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                  
Hit:8 http://ppa.launchpad.net/kubuntu-ppa/ppa/ubuntu bionic InRelease                                                                                    
Hit:9 http://ppa.launchpad.net/mkusb/ppa/ubuntu bionic InRelease                             
Hit:10 http://ppa.launchpad.net/teejee2008/ppa/ubuntu bionic InRelease                        
Hit:11 http://ppa.launchpad.net/yannubuntu/boot-repair/ubuntu bionic InRelease                
Ign:12 https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs vscodium InRelease
Err:13 https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs vscodium Release
  404  Not Found [IP: 35.231.145.151 443]
Reading package lists... Done                      
E: The repository 'https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs vscodium Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by BasRoufs** [comment]
Pls. keep me updated on bug fixes.

**Comment by BasRoufs** [comment]
PS. I have tried to fix the problem by:
uninstalling VS Codium;
removing the repo;
adding the repo manually via the instructions at this page:
https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo
then installing again vscodium.

I can add the repo, however, I cannot update it.
I cannot install any more vscodium - that package cannot be located any more.

**Comment by davidrhoderick** [comment]
Can confirm that this is an issue.  I cannot update anything on my machine if I include the VSCodium Repo and will have to disable it, disabling automatic updates of VSCodium in order to use the rest of my operating system.

**Comment by zapateo** [comment]
Similar problem on Fedora 31 Workstation.

If I follow the steps on the page https://vscodium.com/ at the `Fedora / Centos / OpenSUSE (rpm package)` section I get:

```
No match for argument: codium
```

Listing the packages in the repository with `sudo dnf repository-packages gitlab.com_paulcarroty_vscodium_repo list` returns an empty list.

Such repository used to work as expected until the release of 1.43.0.

**Comment by BasRoufs** [comment]
Hello Roderick and Everybody.

> Can confirm that this is an issue. I cannot update anything on my machine if I include the VSCodium
>Repo and will have to disable it, disabling automatic updates of VSCodium in order to use the rest of > my operating system.

Same for me. I have just removed the VSCodium repo in order to update
my machine.
Yours.

Bas.

**Comment by BasRoufs** [comment]
My system is:

Kubuntu 18.04 LTS.

Op do 12 mrt. 2020 om 12:19 schreef Bas Roufs <basroufs@gmail.com>:
>
> Hello Roderick and Everybody.
>
> > Can confirm that this is an issue. I cannot update anything on my machine if I include the VSCodium
> >Repo and will have to disable it, disabling automatic updates of VSCodium in order to use the rest of > my operating system.
>
> Same for me. I have just removed the VSCodium repo in order to update
> my machine.
> Yours.
>
> Bas.



-- 

Bas G. Roufs

Utrecht, NL, E. BasRoufs@gmail.com; Mob. +31 6 446 835 10;

**Comment by cradcore** [comment]
I'm getting a similar issue. Also, there is no .deb file in the new 1.43 release

**Comment by stripedpajamas** [comment]
Have triggered rebuild, should have the 1.43 assets presently. Sorry for the mixup.

**Comment by yermulnik** [comment]
@stripedpajamas How long would it take? I'm still seeing the issue:
```
> apt update
[…]
Err:23 https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs vscodium Release
  404  Not Found
[…]
E: The repository 'https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs vscodium Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by BasRoufs** [comment]
Hellelujah! 

Thanks everybody for your efforts! Issue resolved. I did manage to add the repo again, to update it successfully and to reinstall VS Codium.

So, it works again seemingly correctly. See report below.

Yours.

Bas G. Roufs, Utrecht, NL.


bas@Viaconsensus-iter:~$ sudo apt update
Hit:1 http://nl.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://ppa.launchpad.net/bluetooth/bluez/ubuntu bionic InRelease                                                                                                                         
Hit:3 http://nl.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                                                             
Hit:4 http://nl.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                                                           
Hit:5 https://updates.signal.org/desktop/apt xenial InRelease                                                                                                                                  
Hit:6 http://ppa.launchpad.net/gezakovacs/ppa/ubuntu bionic InRelease                                                                     
Hit:7 http://ppa.launchpad.net/kubuntu-ppa/ppa/ubuntu bionic InRelease                                              
Get:8 http://security.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]                   
Hit:9 http://ppa.launchpad.net/mkusb/ppa/ubuntu bionic InRelease                                                             
Hit:10 http://ppa.launchpad.net/teejee2008/ppa/ubuntu bionic InRelease                                                       
Hit:11 http://ppa.launchpad.net/yannubuntu/boot-repair/ubuntu bionic InRelease                                                                             
Get:12 https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs vscodium InRelease [3828 B]                                                     
Get:13 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [38,6 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/main DEP-11 48x48 Icons [17,6 kB]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/main DEP-11 64x64 Icons [41,5 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/main DEP-11 128x128 Icons [97,7 kB]
Get:17 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [42,1 kB]
Get:18 http://security.ubuntu.com/ubuntu bionic-security/universe DEP-11 48x48 Icons [16,4 kB]
Get:19 http://security.ubuntu.com/ubuntu bionic-security/universe DEP-11 64x64 Icons [116 kB]
Get:20 http://security.ubuntu.com/ubuntu bionic-security/universe DEP-11 128x128 Icons [181 kB]
Get:21 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 DEP-11 Metadata [2464 B]
Get:22 https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs vscodium/main amd64 Packages [604 B]
Fetched 647 kB in 3s (246 kB/s)    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up-to-date.
bas@Viaconsensus-iter:~$ sudo apt install codium
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed                                                                                                                                                    
  codium                                                                                                                                                                                        
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 64,1 MB of archives.
After this operation, 269 MB of additional disk space will be used.
Get:1 https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs vscodium/main amd64 codium amd64 1.43.0-1584034111 [64,1 MB]
Fetched 64,1 MB in 34s (1889 kB/s)                                                                                                                                                             
Selecting previously unselected package codium.
(Reading database ... 368461 files and directories currently installed.)
Preparing to unpack .../codium_1.43.0-1584034111_amd64.deb ...
Unpacking codium (1.43.0-1584034111) ...
Setting up codium (1.43.0-1584034111) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
bas@Viaconsensus-iter:~$
