### ISSUE TITLE
Is the latest release 1.43.2 or 1.44? 

### ISSUE THREAD

**Issue by stevenj** [VSCodium/vscodium#376]
VSCodium (on ubuntu) complains that its not the latest release, that 1.44 is.

The releases page shows that 1.43.2 is the latest release, but its also numbered 1.44

The distributions in 1.44 are split between 1.44 or 1.43.2

Which is it?

**Comment by athrunsun** [comment]
Looks like newer versions are released under tag 1.43.2, while this tag doesn't match release title "1.44.1", it is also marked as "Latest release".

![1](https://user-images.githubusercontent.com/1920454/79304996-17eac200-7f25-11ea-82fe-c3d266d82802.png)

Note that release titled "1.44.1" has 74 assets, scroll down and you can see assets belonging to version 1.44.0, 1.44.1.

Don't know if this is intentional or by mistake though.

**Comment by stripedpajamas** [comment]
Yeah I think there was something going on with upstream tagging; definitely some flub happened last month and I think it has affected things this month as well.

As of yesterday, I am seeing a proper 1.44.2 release tied to a proper 1.44.2 tag, and my version (mac os x) auto updated properly. 

The latest release (at the time of writing this) is 1.44.2.

**Comment by stevenj** [comment]
as did mine
