### ISSUE TITLE
vscodium connects to microsoft ip after startup

### ISSUE THREAD

**Issue by wibrt** [VSCodium/vscodium#377]
**Describe the bug**
start vscodium

**Please confirm that this problem is VSCodium-specific**
no ms vscode installed

**To Reproduce**
1. check netstat -at
2. start vscodium
3. check netstat -at again (or watch)
4. see added connection to 13.107.42.18:https

**Expected behavior**
not a connection to ms, as part of the goal of vscode

**Desktop (please complete the following information):**
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-09T10:44:46.342Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-0.bpo.4-amd64 snap

**Comment by wibrt** [comment]
it seems that this behaviour can be disabled (and could thus be the default setting):

Disable all
@tag:usesOnlineServices
(except npm: fetch online package info)

**Comment by paulcarroty** [comment]
It's probably VSC checks for extensions update, got it too:

`tcp        0      0 laptop:60014     13.107.42.18:https      ESTABLISHED`

```
$ host marketplace.visualstudio.com
marketplace.visualstudio.com has address **13.107.42.18**
marketplace.visualstudio.com has IPv6 address 2620:1ec:a92::175
```

**Comment by stripedpajamas** [comment]
Yes -- as @paulcarroty mentioned, this is because VSCodium uses Microsoft's extension marketplace. Currently, VSCodium disables _telemetry_ by default (not all network calls), which has its own section in Visual Studio Code's settings page:

![image](https://user-images.githubusercontent.com/2707340/79697910-4e348400-823a-11ea-9a20-b7d60425008a.png)

We have a section in our docs ([here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#getting-all-the-telemetry-out)) that talks about the settings that use online services. We don't disable these by default because they can interfere with what people have come to expect from VSCode/VSCodium (e.g. autoupdating). Each person can decide whether or not they're ok with those settings on a case-by-case basis.
