### ISSUE TITLE
Edit resources\app\out\vs\workbench\workbench.desktop.main.css ?

### ISSUE THREAD

**Issue by exec228** [VSCodium/vscodium#383]
Salut!

**Describe the bug**

Not a bug.
Interface uses Segoe font which makes my eyes bleed.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

This problem is NOT VSCodium specific.
Yet, original VSCode does not have a working support channel. It's broken.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

I haven't found issues related to workbench.desktop.main.css here.

**To Reproduce**

1.Start VSCodium
2.Behold hated Segoe font everywhere in UI.

**Expected behavior**

I would like to ask you to remove integrity check from workbench.desktop.main.css
Because the only working method to set Verdana for UI is to replace "Segoe WPC" string with "Verdana".
After that, MS and you report that "Your VSCodium installation appears to be corrupt. Please reinstall."

**Screenshots**

Obvious

**Desktop (please complete the following information):**

Windows 10x64
VSCodium 1.44.2

**Additional context**

I would be so happy to get rid of Segoe on informational pages, like "extension description" or "what's new" too.

**Comment by stripedpajamas** [comment]
Hi @exec228 👋 

Unfortunately, it is out of the scope of this project to change VSCode's internal integrity checking logic in any way. The best course of action (and I know this is the slow and potentially unfruitful thing to do) is to log an issue in the [vscode](https://github.com/microsoft/vscode/issues) repo asking that the main UI font be customizable instead of hard-coded.
