### ISSUE TITLE
Too much suspicious traffic

### ISSUE THREAD

**Issue by megastallman** [VSCodium/vscodium#407]
Hi guys! Presumably, VSCodium is not completely clean off passive telemetry at least. I've just ran tcpdump and got tons of requests to the following hosts, after starting VSCodium:
```
marketplace.visualstudio.com
github.map.fastly.net
raw.githubusercontent.com
13.107.42.18 - some necrosoft-azure host
```
Is it possible just to make the application shut up and stop phoning home at every start? I've disabled update checks before and installed a couple of additions I could possibly need.

**Comment by Rowisi** [comment]
you have to disable `check for updates` too. This option will notify you that there are some outdated extension without updating them if you have `auto update` disabled.

**Comment by megastallman** [comment]
My appreciates to developers! I've unchecked the extensions update option. Also, VSCodium update option was unchecked earlier. Now it keeps pretty silent. I'm going to close the issue in a week if don't notice anything else,

**Comment by megastallman** [comment]
No, still connects to `raw.githubusercontent.com(199.232.16.133)`

**Comment by filipre** [comment]
Is it possible to run Wireshark to see to which file it exactly connects to?

**Comment by Rowisi** [comment]
@megastallman thats VScodium update api that checks for a new version.

you can check it here https://github.com/VSCodium/update-api/blob/master/api/update/index.js

you'll find the url string at line 39:

`const VERSION_BASE_URL = 'https://raw.githubusercontent.com/VSCodium/versions/master'`

**Comment by megastallman** [comment]
Ok, thanks! that means I couldn't disable autoupdates.

**Comment by stripedpajamas** [comment]
No that doesn't sound right. The update API does call GitHub, but that wouldn't show up on the local computer's network activity. 

@megastallman do you have any extensions installed? Are you opening a project that lives on GitHub?

**Comment by megastallman** [comment]
I'm opening local projects only. Btw, just disabled all extensions and VSCodium started connecting to `marketplace.visualstudio.com` every time I start it.

**Comment by stripedpajamas** [comment]
Yes connecting the marketplace service is normal. You wouldn't be able to stop that connection except by turning off the extension marketplace completely. I can try to dig through some of Microsoft's code to see if the raw GH url is in there.

To be clear (and this has come up in past), VSCodium doesn't advertise that no network traffic will happen within it. We only "disable telemetry by default" which is a setting within the app. MS isn't up front about the different ways their app calls home, so it's possible the network calls you are seeing represent something we missed. The action item for this issue is to see if there is some reference to the IP or hostname you found inside the vscode code base. If so we can then determine if it's telemetry related (doubtful, since they are careful to honor the app setting). It is more likely related to some "feature" of vscode and I'd like to figure out what the feature is.

**Comment by megastallman** [comment]
Yeah, I get the problem. So, due to package management and tons of other features the application can not be silent. And of course, necrosoft can use the same endpoints, especially belonging to their domains for any data. Including passive telemetry. Say, "this particular guy, is doing python, salt and yaml", according to the plugins used.
So, I'm closing the issue, but I'll try reading the code, sniff traffic and if I find anything more suspicious, I'll put it here. 
Making it silent could be a bigger effort... Say, adding an option and dozens of if conditionals or so...

**Comment by megastallman** [comment]
Settings(search for "update"):

Update Mode - none[see above]
Update Show Release Notes - [ ]
Extensions Auto Check Updates - [ ]
Extensions Auto Update - [ ]
