### ISSUE TITLE
Auto Updating Support

### ISSUE THREAD

**Issue by ganapativs** [VSCodium/vscodium#41]
How does auto updating works here? how are we pushing the new update?

also anyone has idea about how to configure custom `update.channel`?

**Comment by JL2210** [comment]
Use the deb repository. See the README.

**Comment by stripedpajamas** [comment]
The deb repository might be a good idea for Linux users. For Mac users we will have to figure something else out. It's not the best experience having to check the repo for updates or ask brew for updates. This could use some discussion.

**Comment by JL2210** [comment]
Brew can auto-update. In Debian, auto-updates do not happen automatically. You still have to type `sudo apt-get update && sudo apt-get upgrade`.

**Comment by stripedpajamas** [comment]
I think we can get something like that working. I need to investigate out it currently works in vscode

**Comment by ganapativs** [comment]
Yes, there must be a proper interface for that feature, we need to check how to configure the same. I'll see if I can figure out something.

**Comment by tynx** [comment]
In case anyone want's to do it with a simple bash-"script", that you can trigger as often as you like...
```bash
wget -q -O /tmp/vscodium.deb $(wget -O- -q https://api.github.com/repos/VSCodium/vscodium/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep "amd64.deb") && sudo apt -f install /tmp/vscodium.deb && rm /tmp/vscodium.deb
```
Note: This Only supports dpkg/apt and amd64... :-)

**Comment by tynx** [comment]
Out of personal interesst I looked into the source of the updater-mechanism...

https://github.com/Microsoft/vscode/blob/bb23217d1ef48ff6549b214162b36e8b8306e943/build/gulpfile.vscode.linux.js#L84

It seems that the update mechanisms hits this URL. See the following folder for the concrete implementation of the updater-service. the abstract implementation contains the basic URL-schemantics for all platforms and the actual "update-checking" happens in the platform-specific implementations.
https://github.com/Microsoft/vscode/tree/master/src/vs/platform/update/electron-main

for linux:
https://github.com/Microsoft/vscode/blob/ab63c5d4c98a7deaf4974e8a8723f8dd5d7278b9/src/vs/platform/update/electron-main/updateService.linux.ts#L39

I'd probably try to change the update-url in the gulp-build-process to localhost or similar and would see what gets requested and try to respond... Maybe that insight helps - if not just ignore my input :-)

**Comment by ganapativs** [comment]
Found some more resources when opened `Applications ▸ Visual Studio Code ▸ Show package contents(Right click) ▸ Contents⁩ ▸ ⁨Resources⁩ ▸ ⁨app⁩ ▸ product.json` on OSX VSCode.

The `product.json` file has all the information about the build. 
Update points to https://vscode-update.azurewebsites.net and these are the update urls.

https://vscode-update.azurewebsites.net/api/update/darwin/stable/VERSION
https://vscode-update.azurewebsites.net/api/update/darwin/insider/VERSION

If we can configure custom update URL & replicate above response format, things should probably work?

**Comment by tynx** [comment]
I would guess so as well. I know that you can host static pages on github (??repo??.github.io or something...)

Maye on each build push a file with the necessary information into the repo-root and host it directly from the github itself?

**Comment by paulcarroty** [comment]
> I know that you can host static pages on github 

We can just host the one json directly in vscodium repo.

**Comment by stripedpajamas** [comment]
@ganapativs @tynx thank you both for digging in. Yes-- this is perfect, we can easily host a JSON file that has the latest version with its hash and download link in the repo and update it at build time. When I have a few minutes I'll dig in, but PRs are welcome in the meantime. Again thank you all for digging in, as this is a piece of the vscodium puzzle that was really in need of solving 👍

**Comment by stripedpajamas** [comment]
Circling back to this today... I think the next steps are:

- Figure out what populates the information in this file: https://vscode-update.azurewebsites.net/api/update/darwin/stable/VERSION
  - specifically `version` , `hash`, and `sha256hash`
- Generate that info (as organically as possible) post-build in VSCodium
- Setup committing the updated VERSION file post-build to the repo (pending #47 being merged)

I'll start investigating

**Comment by stripedpajamas** [comment]
Another step is that updates apparently won't work unless the app is signed. I'm not sure how to sign the app during Travis build so that is something I've got to figure out.

**Comment by stripedpajamas** [comment]
@ganapativs vscode uses electron's autoupdater functionality, and the electron docs [here](https://electronjs.org/docs/api/auto-updater#macos) say the app needs to be signed for Mac OS.

We don't currently sign the builds. Do you know how to do this in an safe automated way?

**Comment by ganapativs** [comment]
@stripedpajamas Okay, I don't know much about signing desktop apps, have to figure it out.

**Comment by batjko** [comment]
Also, not to be pedantic, but Windows users would surely also appreciate the ability, as they have had it for Standard vsc.

**Comment by stripedpajamas** [comment]
Absolutely, @batjko. This is definitely something that should be near the top of the priority list as it is a big shortcoming of VSCodium as compared to VSC.

**Comment by jakobsudau** [comment]
Hello! 
As a new VSCodium user (awesome project) just my two cents, this functionality is definitively needed! Hope you guys can figure it out :)

**Comment by stripedpajamas** [comment]
Some more notes to keep the ball rolling and so I don't forget:

- the full URL used to check for updates is `${product.updateUrl}/api/update/${platform}/${quality}/${product.commit}`, where `product.<value>` comes from the `product.json` file
- `product.commit` is populated automatically at build time (properly)
- `platform` can be `darwin`, `linux-<arch>`, `win32-[x64]-<archive|user>`
- we aren't currently setting `quality` and if it isn't set, all the update logic is disabled
- we can't use a JSON file because response codes are important to this process
  - vscode uses Electron's autoupdater for Mac updates and custom logic for Windows + Linux. All three are expecting 200 if it should download an update and 204 if it shouldn't. On 200, the client expects the JSON blob (this accords with Squirrel, the underlying tech in Electron's autoupdater)
  - this can be seen with the current update API [update.code.visualstudio.com](https://update.code.visualstudio.com) (`51b0b28134d51361cf996d2f0a1c698247aeabd8` is the commit hash of 1.33.1 in the vscode repo):
  ```bash
  $ curl -I https://update.code.visualstudio.com/api/update/darwin/stable/51b0b28134d51361cf996d2f0a1c698247aeabd8
  HTTP/1.1 204 No Content
  [...]
  $ curl -I https://update.code.visualstudio.com/api/update/darwin/stable/anythingelse
  HTTP/1.1 200 OK
  [...]
  ```

So might need to stand up a small update server to handle the details.

**Comment by stripedpajamas** [comment]
Ok I made some progress on this over the past couple of days. Here is an update:

- created the [VSCodium/update-api](https://github.com/VSCodium/update-api) repo and the [VSCodium/versions](https://github.com/VSCodium/versions) repo
- built out a lambda in update-api that responds similarly to update.code.visualstudio.com and set it up with [Now](https://zeit.co/now) to deploy to vscodium.now.sh
  ```bash
  $ curl -I https://vscodium.now.sh/api/update/darwin/stable/some-bogus-commit-hash
  HTTP/2 200
  [...]
  $ curl https://vscodium.now.sh/api/update/darwin/stable/some-bogus-commit-hash | jq
    {
      "url": "https://github.com/VSCodium/vscodium/releases/download/1.34.0/VSCodium-darwin-1.34.0.zip",
      "name": "1.34.0",
      "version": "a622c65b2c713c890fcf4fbf07cf34049d5fe758",
      "productVersion": "1.34.0",
      "hash": "768e876321bf52e337d5f05bc24f06246c8d1877",
      "timestamp": "1558030458353",
      "sha256hash": "b1c3fd7b421d8e97af7e0556956e0d19c06031526a92b3ca19b8103cd167455d"
    }
  $ curl -I https://vscodium.now.sh/api/update/darwin/stable/a622c65b2c713c890fcf4fbf07cf34049d5fe758
  HTTP/2 204
  [...]
  $ curl https://vscodium.now.sh/api/update/darwin/stable/a622c65b2c713c890fcf4fbf07cf34049d5fe758
  [no content]
  ```
- the returned JSON blob is retrieved from VSCodium/versions for the specific os/arch passed into the API
- I added [a script](https://github.com/VSCodium/vscodium/blob/master/update_version.sh) that commits the version JSON file after a successful build+deploy of VSCodium
- Currently the script is only set up for Linux + Darwin, so I made a new task in [the project](https://github.com/VSCodium/vscodium/projects/1) to get it working for Windows builds as well


Testing everything out is not intuitive, so I will probably have to write up a Contributing Guide pretty soon that covers VSCodium, the update API, and the versions repo. 

I will try to test it out with an older version of VSCodium and see how it responds to the API.

**Comment by stripedpajamas** [comment]
I was successfully auto-updated on my Mac using the new service 🎉 

Testing steps:
- downloaded an old version (1.33.0) of VSCodium
- edited `product.json` to include `quality: stable`, `updateUrl: vscodium.now.sh`, and `releaseNotesUrl: https://go.microsoft.com/fwlink/?LinkID=533483#vscode` (so that updates are not silent)
- signed the binary (since signing had not been implemented by 1.33.0)
- opened the app and watched the Output | Log (Main) window
- it hit the update API (which I could also see from the lambda logs), determined it was out of date, and downloaded the new file
- I closed/reopened the app and found that I was on version 1.34.0

I updated the project to include adding `releaseNotesUrl` to the product.json pre-build.

Notes on Linux: I don't know if anyone has had experience with autoupdates on Linux, but since the API returns the `tar.gz` file link, I am doubtful that it autoupdates. I think with the introduction of the snap package things might have changed, but VSCodium hasn't gotten snap support figured out yet. If anyone has more information about how it works, please comment.

**Comment by stripedpajamas** [comment]
Good news -- I updated the version updater to support Windows and then tested auto updating on a Windows machine (x64, user install) -- it worked 🎉 

Next step according to [the project](https://github.com/VSCodium/vscodium/projects/1) is to add two fields to the product.json file and then call it a day (wait for the next MS release). Actually will have to wait for two more MS releases -- the first will make VSCodium start checking for updates, the second will be a new version that VSCodium downloads + installs.

**Comment by thymbahutymba** [comment]
Check for update return server error 404.

Version: 1.35.0 (system setup)
Commit: db1afbd17a1c66db7ac8cf62a03d7b4db3aca70b
Date: 2019-06-11T04:56:38.833Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

![image](https://user-images.githubusercontent.com/23526758/59870884-a094e200-9396-11e9-87f8-ca7069e11374.png)

**Comment by stripedpajamas** [comment]
System setup updates are not supported. I'm not certain that they're supported by Microsoft either because it looked like the update code specified user or archive.

**Comment by thymbahutymba** [comment]
Yes, they are supported. 

I also tried to install the user setup 1.35.0 for check the update of 1.35.1 and the message shown was that vscodium is already updated, it's normal? There even should be a "pop-up message" on bottom right side, like vscode, that alert me about an update?

**Comment by resynth1943** [comment]
Is this even supported on Linux with *VSCode*? When they request you update the software, it navigates you to https://code.visualstudio.com to download a `deb` / `rpm`, so I'm not sure if this can be done on Linux.

**Comment by wpfan2099** [comment]
hi there - i need to update vscodium on mxlinux 

at the moment i am on mx-linux version 19.2

running vscodium: 1.47.3

want to update to the newest vscodium: 1.52.1

saw that we can go probably this way: is this an apropiate way:

https://www.google.com/search?ei=Y9MAYMynNJCZkwXfu6NY&q=how+to+upgrade+vscodium+on+linux&oq=how+to+upgrade+vscodium+on+l&gs_lcp=CgZwc3ktYWIQAxgAMgUIIRCgATIFCCEQoAEyBQghEKABOgQIABBHOgQIABANOgQILhANOgYIABANEAo6CQgAEEMQRhD_AToECAAQQzoECC4QQzoICC4QsQMQgwE6BwgAELEDEEM6AgguOggIABCxAxCDAToCCAA6BggAEBYQHjoECAAQEzoICAAQFhAeEBM6CggAEBYQChAeEBM6CggAEA0QChAeEBM6BAghEBVQsAFYhasCYP_BAmgQcAJ4AIABpgSIAfgvkgEKMzYuNy4yLjUtM5gBAKABAaABAqoBB2d3cy13aXrIAQjAAQE&sclient=psy-ab#kpvalbx=_ldMAYIjbEpqakgXFnZFQ13

the folks there have got a three-step-solution

**a.** add gpg-key of the repository

**b.** add  the repository

**c**. update then install vscodium

look forward to hear from you

**Comment by resynth1943** [comment]
Hiya,

> saw that we can go probably this way: is this an apropiate way:

Not opening that. Instead of sharing mysterious SERP
links, perhaps you could investigate the options made available
by the VSCodium developers? :slightly_smiling_face: 

I just update VSCodium via my distribution's native package manager. 
I would advise disabling the 'auto-update' in most cases, as it does nothing.

> - a. add gpg-key of the repository
> - b. add the repository
> - c. update then install vscodium

I don't know what that means, but I suggest you investigate the packaging
solution for your Linux distribution.

https://github.com/VSCodium/vscodium#install-with-package-manager

P.S. Sending mysterious links is off-putting.
