### ISSUE TITLE
Big problem when updated from 1.45.1 to 1.46.0

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#421]
* HomeDir\.vscode-oss\extensions is empty, all the installed extenstions gone
* Extenstion market not work properly, eg:
  * can't find M$ C++ extenstion
  * vscode-icon extention shows wrong rating stars and downloaded count
![image](https://user-images.githubusercontent.com/3665590/84649372-ff088800-af38-11ea-9131-c82c371b3db1.png)

**Comment by ThinkTwiceCodeOnce-prog** [comment]
In fact, this is not a bug. Since the last update the market place by Microsoft for extensions is replaced by [open-vsx.org](http://open-vsx.org/). It is a new **open-source** registry for extensions and therefore not all of them exist there (by now). Conditioned by licencing some of Microsoft's own extensions cannot be available there.

For information about this (intended) change you can read the docs: [https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace)

Btw, great step towards more **privacy** here by detaching Microsofts proprietary market place by default.

**Comment by playgithub** [comment]
LOL, born from M$, then isolated from M$
