### ISSUE TITLE
Why use built-in extenstions?

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#423]
I think it's better for user to choose freely.
By disabling some built-in extention and install another is not simple enough.
If the reason is easy to use by default, I don't think so, it's better to suppose the user should be professional, and vscodium should be professional, proper professional = simple and powerful.

**Comment by dalisoft** [comment]
I also would like remove some of built-in extensions like M$ auth, GitHub and always disable after installing.

**Comment by spoenemann** [comment]
Hint: The VS Code built-in extensions are available on https://open-vsx.org, see e.g. [github-authentication](https://open-vsx.org/extension/vscode/github-authentication). This means that you can easily install such extensions even if they are not bundled with the product. This is not possible with the Microsoft Marketplace because it does not host the built-in extensions.

**Comment by playgithub** [comment]
To make it clear:
1. vscode has no built-in extension, free to install/uninstall any extension
2. vscodium has a lot that can't be uninstallled

**Comment by spoenemann** [comment]
> vscode has no built-in extension

vscode has a lot of built-in extensions:
https://github.com/microsoft/vscode/tree/master/extensions

You can neither install nor uninstall these, and they are not shown in the product.json file. In addition, vscode also includes `ms-vscode.node-debug`, `ms-vscode.node-debug2`, `ms-vscode.references-view`, `ms-vscode.js-debug-companion`, `ms-vscode.js-debug` and `ms-vscode.vscode-js-profile-table` (listed in product.json).

**Comment by playgithub** [comment]
all ms-*, I think vscodium should make them a extension if possible, that'll be better instead of adding more built-in extenstions.

**Comment by stripedpajamas** [comment]
VSCodium isn't adding anything here; we are building the code that is in Microsoft's `vscode` repo. I am confused as to what the purpose of this issue is @playgithub -- are you asking us to disable all of Microsoft's built-in extensions by default in VSCodium? I don't think that can be done without messing with MS's build scripts directly, which I am not too interested in doing.

**Comment by playgithub** [comment]
It's ok to leave ms' build-in extentions, but vscodium 1.47.0 adds a lot of extra built-in extentions, it's not soo good.
In my opinion, just remove the telemetry is good enough.
