### ISSUE TITLE
Missing fonts in snap package

### ISSUE THREAD

**Issue by abitrolly** [VSCodium/vscodium#426]
All system dialogs in version 1.46.0 from `snap` package are rendered with no font glyphs. Folder selection, about, etc.

![image](https://user-images.githubusercontent.com/8781107/84943891-b80fc380-b0ed-11ea-9dce-6f9bada0f9e9.png)

```
[main 2020-06-17T19:55:01.882Z] menubarService#updateMenubar 1
[main 2020-06-17T19:55:06.916Z] menubar#runActionInRenderer { type: 'commandId', commandId: 'workbench.action.showAboutDialog' }
[225991:0617/225506.922960:INFO:CONSOLE(1669)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.showAboutDialog", source: file:///var/lib/snapd/snap/codium/42/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (1669)
Gtk-Message: 22:55:06.940: GtkDialog mapped without a transient parent. This is discouraged.
```

This is Fedora 32 with GNOME on Wayland,

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. `snap install codium`
2. `codium`
3. Help -> About

**Comment by abitrolly** [comment]
Hi @popey. Do you know what's going on with the snap? This problem in this thread looks very similar https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/7

**Comment by bkis** [comment]
I suddenly have the same issue (Pop!_OS 20.10, VSCodium 1.51.1 via snap) - almost half a year later:

![image](https://user-images.githubusercontent.com/9215743/100359578-09ef3a80-2ff8-11eb-846f-a97bb89a3953.png)

**Comment by abitrolly** [comment]
@bkis `snapcrafters` could fix that https://github.com/snapcrafters/codium/issues/6

**Comment by constantlam** [comment]
I had this problem today too under Ubuntu 20.10, when opening a file or folder or displaying a dialog box. I tried deleting and rebuilding the font cache, but the problem persisted. It appears that VS Codium only showed this problem, other programs like Gedit libreoffice worked normally. I have found out that the problem was that I installed a variable truetype font (i.e. one font file for all font weights and styles, instead a separate file for each weight and style) on my system I removed and rebuilt the font cache again. Removing this variable truetype font file solved the dialog box problem. It appears that the font cache with a variable font conflicts with VS Codium.

**Comment by abitrolly** [comment]
Nice. That's at least something to try. Maybe a problem with `fontconfig` in snap being "too stable". At least switching to `core20` in snap may worth trying. Or using some recommended tools like `electron-builder` as an alternative way of packing.

**Comment by daiyam** [comment]
For the snap expert out there, is it a VSCodium specific issue?
When trying to install snap on my Arch, I went to read the doc and found this: https://wiki.archlinux.org/title/Snap#Text_unreadable
So it's letting me wonder...

**Comment by bkis** [comment]
> For the snap expert out there, is it a VSCodium specific issue?

I am not the snap expert you are looking for, but [it looks like a problem with the VSCodium snap](https://github.com/snapcrafters/codium/issues/6#issuecomment-845828274) and not with VSCodium itself.

**Comment by daiyam** [comment]
The following commands should fix the issue:
```
rm -rf ~/.cache/fontconfig 
rm -rf ~/snap/codium/common/.cache
fc-cache -r
```

**Comment by freeman-h** [comment]
> 

Thank you, that second line was the kicker.

**Comment by abitrolly** [comment]
For the snap on Fedora 35 it didn't help. @freeman-h what OS do you use?

**Comment by g7fernandes** [comment]
This error is somehow related to electron apps integration. The same occours in slack and MS Teams.

**Comment by eshate** [comment]
Hey, I've just encountered the same issue. 
Snap `1.73.1.22314` on PopOS

I found this thread and used this from @daiyam 
```
rm -rf ~/.cache/fontconfig 
rm -rf ~/snap/codium/common/.cache
fc-cache -r
```

And it worked. But after a while it happened again...
The possibility is that it happened, because I've cleaned also my `$HOME` temp folder, so maybe because of that. I cannot reproduce, but I will have an eye if it will come back.

Interesting for me is what @constantlam wrote:
> Removing this variable truetype font file solved the dialog box problem. It appears that the font cache with a variable font conflicts with VS Codium.

But I have so many fonts that I cannot even check if it's true. And I need them, so it will not work for me.

**Comment by patrickuhlmann** [comment]
I also just encountered the issue on ArchLinux. The three commands above didn't work for me. Still can't read the dialogs

**Comment by mcmahanp** [comment]
FYI still an issue on Ubuntu 23.04 with Gnome 44.3 and VSCodium 1.83.1.
But clearing the font cache a la [this comment](https://github.com/VSCodium/vscodium/issues/426#issuecomment-1025415690) did fix it.

**Comment by popey** [comment]
Snapcrafters no longer publishes vscodium since December 2021. 
Issues should be filed at https://github.com/VSCodium/vscodium/issues
