### ISSUE TITLE
Intellisense/Autocompletion not working for Python

### ISSUE THREAD

**Issue by zhxh1** [VSCodium/vscodium#427]
**Describe the bug**
Intellisense/Autocompletion not working for Python.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open a new empty window
2. Create a new file `test.py`
3. type `import sy`
4. Press `ctrl + enter`
5. Should auto-complete to  `import sys` but shows `No suggestions`

**Expected behavior**
Intellisense/Autocompletion works.

**Desktop (please complete the following information):**
 - OS: `Ubuntu 20.04`
 - Architecture `x64`
- VSCodium: `1.46.0`

**Comment by br3ndonland** [comment]
I had this issue as well, but I don't think it relates to VSCodium specifically. It's a known issue with the Python extension. It was reported in microsoft/vscode-python#12429, and should be fixed in an upcoming release (via microsoft/vscode-python#12433).

In the meantime, you can switch to the [Microsoft Python language server](https://github.com/microsoft/python-language-server). It's open-source, Apache 2.0 licensed, doesn't require a connection to the Microsoft marketplace, and works with VSCodium. You just need to update your VSCodium _settings.json_, and it will download automatically.

Your _settings.json_ might have some entries like this:

```json
{
  "python.jediEnabled": true,
  "python.languageServer": "Jedi"
}
```

The `"python.jediEnabled"` key is now deprecated, so you can remove it, and then change your language server to Microsoft:

```json
{
  "python.languageServer": "Microsoft"
}
```
