### ISSUE TITLE
Cannot find extension from VS Code Marketplace

### ISSUE THREAD

**Issue by danikgan** [VSCodium/vscodium#439]
I want to install the following extension https://marketplace.visualstudio.com/items?itemName=marp-team.marp-vscode. It appears in VSCode but not in VSCodium. I find this strange. Is this intention behaviour?

**Comment by rohan-sircar** [comment]
VSCodium moved to open-vsx.org as the extensions provider since version 1.46.0(please refer to the release notes and the ![readme](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace).

You therefore have 3 options - 
1. Download the extensions manually
2. Request extension maintainer to publish on open-vsx.org
2. Downgrade VSCodium to 1.45.x, which is the last version that did not switch to open-vsx
