### ISSUE TITLE
Not able to install on macOS Catalina

### ISSUE THREAD

**Issue by ramanNarasimhan77** [VSCodium/vscodium#459]
Hello,

I get the following message on macOS Catalina when I try to download [VSCodium.1.47.2.dmg](https://github.com/VSCodium/vscodium/releases/download/1.47.2/VSCodium.1.47.2.dmg) and then open the app

<img width="426" alt="image" src="https://user-images.githubusercontent.com/52691361/87866016-bad63080-c999-11ea-935d-b2e4e9227d9a.png">

Also tried to use brew, but I don't have admin rights on this laptop so could not install using brew.

```
$ brew cask install vscodium
....
==> Downloading https://github.com/VSCodium/vscodium/releases/download/1.47.2/VSCodium.1.47.2.dmg
.......
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'vscodium'.
==> Installing Cask vscodium
==> Creating Caskroom at /usr/local/Caskroom
==> We'll set permissions properly so we won't need sudo in the future.
Password:
```

Is there any viable workaround?

**Comment by ramanNarasimhan77** [comment]
I tried the solution given in #370 but that did not solve my problem. I get the same error then too.

Probably because I did not install using homebrew

**Comment by stripedpajamas** [comment]
This is expected behavior on Mac OS currently, since we haven't notarized the app (#324). I don't think you will be able to get around it without admin permissions (you need admin permissions just one time). 

Steps that don't require holding down keys:

1. Try opening VSCodium
1. Get the error message
1. Open System Preferences | Security and click the Unblock button at the bottom
1. Try opening VSCodium (should open fine now)

The Unblock button will most likely be unavailable to non-admin user.
