### ISSUE TITLE
Integrated terminal does not open on keyboard shortcut on macOS

### ISSUE THREAD

**Issue by nicdoye** [VSCodium/vscodium#462]
**Describe the bug**
Ctrl-` does not launch integrated terminal

**Please confirm that this problem is VSCodium-specific**
- [*] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install VSCodium on macOS 10.15.6
2. Open a project
3. Hit Ctrl-`

**Expected behavior**
Open Integrated Terminal

**Screenshots**

**Desktop (please complete the following information):**

- Version: 1.47.2
- Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
- Date: 2020-07-17T11:10:35.810Z (4 days ago)
- Electron: 7.3.2
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.6.0

**Additional context**
You can get to the terminal by clicking on the warnings/errors in the bottom bar, which opens Problems/Output/Debug Console/Terminal, and then click on "Terminal".
You can also go to Menu Bar->Terminal->New Terminal.

**Comment by stripedpajamas** [comment]
Can you confirm the default keymap is properly set? 
In VSCodium | Preferences | Keyboard Shortcuts 
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/2707340/88741384-5ed77e80-d0f4-11ea-9048-d04455040873.png">

**Comment by nicdoye** [comment]
Hi, upgraded to the latest version this morning, and it's still the same. Here's a screenshot from Keyboard Shortcuts:

**Comment by nicdoye** [comment]
Is there anything I can do to help narrow down what is causing this?

**Comment by yvern** [comment]
Hello, I just had this same issue. Initial setting:
<img width="439" alt="Screenshot 2021-08-24 at 14 20 56" src="https://user-images.githubusercontent.com/18158656/130623867-4ee10f82-bd9e-453c-98e8-244b63b6226b.png">

For some reason, it seems VSCodium recognises `§` as \` (backtick), even so that trying `^ + §` from my keyboard actually opens up the terminal, and on trying to set the keybinding to use ` ^ +` ` it shows another key code:

<img width="403" alt="Screenshot 2021-08-24 at 14 20 08" src="https://user-images.githubusercontent.com/18158656/130623894-521a7f0c-243b-4431-a933-315ef2b02616.png">

Also, no software keymapping here.
