### ISSUE TITLE
PHP Debug don't work 

### ISSUE THREAD

**Issue by zacjack** [VSCodium/vscodium#466]
Hello everyone, thanks in advance for any help.

I'm trying to migrate to VSCodium, but i has a problem with this extension for PHP Debugging

PHP Debug 1.13.0 from felixfbecker

`[2020-07-28 23:16:36.862] [renderer1] [error] timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:3160:190)
    at file:///usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:3159:451
    at async t.RawDebugSession.shutdown (file:///usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:3157:536)`

this work fine on VSCode,

**Comment by T200proX7** [comment]
LINUX / DEBIAN:

I have the same /almost same problem. Xdebug does not listen on the port when clicking on Start Debugging. More just seconds after clicking the button it stop the debug mode.

No there is no port collision with php-fpm and also no config problem.
I tried several ways and xdebug work fine with Sublime or VSCode (but no codium).

**Comment by filakhtov** [comment]
There is #464, so I think that affects all platforms. I am having the same issue on macOS Catalina. There is also a similar report on the Xdebug plugin repo: felixfbecker/vscode-php-debug#414. I think VSCodium builds are messed up presently, because VSCode works just fine.

**Comment by TomaszGasior** [comment]
Maybe it's related to https://github.com/microsoft/vscode/issues/103105 and https://github.com/microsoft/vscode/commit/21e633cc63a58c7403dffbf242e1ce29416c2143.

**Comment by kevinfiol** [comment]
Ah was having this same issue on my Linux Mint machine. Glad to see I'm not alone.

**Comment by TomaszGasior** [comment]
I managed to fix this issue by downloading PHP Debug extension from Microsoft's Visual Studio Marketplace instead of using VSCodium alternative marketplace. It works at least on Linux (Fedora and Ubuntu). Step by step guide is

0. make sure you don't have PHP Debug extension installed;
1. go to https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug and download vsix file using "Resources" → "Download Extension";
2. in VSCodium go to "Extensions" sidebar and then click three dots icon near to "Extensions title;
3. choose "Install from VSIX…" and select downloaded file.

**Comment by brunob** [comment]
nice but strange @TomaszGasior :)

**Comment by brunob** [comment]
FTR, v1.49.0 seems to fix the bug for me : i've removed PHP Debug extension and reinstalled it from the GUI => debug is working.

It may be related to this PR https://github.com/microsoft/vscode/issues/95162

This issue may be closed :)

**Comment by kovacspityu** [comment]
Only VSIX install working for me.

**Comment by lucrus73** [comment]
> This issue may be closed :)

I'm running 1.49.0 and I'm facing this issue.

**Comment by greduan** [comment]
I faced this issue v1.49.3. Tomasz's fix worked for me.

**Comment by eandersons** [comment]
I had the same problem with VSCodium 1.51.1. Solved it by downloading extension from Visual Studio Code marketplace and installing it manually (as per steps described by Tomasz).

**Comment by stripedpajamas** [comment]
Sounds like [the extension on Open VSX](https://open-vsx.org/extension/felixfbecker/php-debug) may be out of date or broken. Based on the extension page, it looks like Open VSX manually published that extension. I recommend reaching out to the developers of the extension (https://github.com/xdebug/vscode-php-debug) and asking them to publish to Open VSX as per [the docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace).

Otherwise, either switching to the MS marketplace or downloading the latest vsix file from the MS marketplace and installing it manually should work, as per @TomaszGasior's comment.

**Comment by ngdangtu-vn** [comment]
@brunob

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-17T00:37:28.692Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux arm64 5.8.0-1010-raspi
```
Mine didn't work.

**Comment by xoxefdp** [comment]
Got sae conditions as @ngdangtu-vn , except os is xubuntu 20.04.
