### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by yusf** [VSCodium/vscodium#477]
First of all: nice to see a new logo. Good job!

I want to inquire about the choice of color. If we take a look at the first run experience, not only are we witnessing a clash between the blue UI color and the eyesore that is the default VSCode status bar, but now there's the VSCodium brand color slammed in there as well. The old logo harmonized completely with the blue UI color. What was the reasoning behind this choice?

![bild](https://user-images.githubusercontent.com/346211/90676163-db74fd00-e25b-11ea-9524-7f1186981a36.png)

I also want to inquire about the empty screen logo variation. A flat version like this would need a counterpart for what the folding shadow does on the main logo.

![bild](https://user-images.githubusercontent.com/346211/90676178-e29c0b00-e25b-11ea-88f3-7d80fd4c58fb.png)

**Comment by jvdp** [comment]
Maybe mostly related to this issue (though I can make a new one if you like;) the logo color clashes / fades a bit with lighter colors behind it: 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/241947/90762448-5a624800-e2e5-11ea-8ed9-d0ddc8c4ab65.png">

Subjectively, I do like the logo, though perhaps not so much the color. Objectively, a border around it (or some other adjustment) would perhaps make it fit in better.

**Comment by olivier-manomano** [comment]
I would add that it looks a bit oversized when sitting close to other rounded icons (at least in the dock of macOS Catalina).

<img width="652" alt="Screenshot 2020-08-20 at 18 30 55" src="https://user-images.githubusercontent.com/57225513/90799589-bb087980-e313-11ea-976c-1009539e6734.png">

Regarding the color, I guess it's a matter of taste. But I also have the impression that it looks very bright on dark backgrounds, while it tends to fade away over grayish backgrounds.

<img width="420" alt="Screenshot 2020-08-20 at 18 40 21" src="https://user-images.githubusercontent.com/57225513/90800407-ed66a680-e314-11ea-8b3d-16abdf12ea3c.png">

**Comment by viridiancity** [comment]
The previous logo was 1,000,000 times better than whatever this new one is.

**Comment by yusf** [comment]
Honestly, now that I've image googled "codium" I really don't see why the old brand mark was discarded. It fits beautifully.

**Comment by Indexerrowaty** [comment]
Imo older logo was WAY WAY better.

**Comment by sys-lectern** [comment]
I really like the new logo, and I think it helps to differentiate/set expectations for the experience since the extensions provider was changed.
I don't really care about the color, but the shape itself is pleasing.

**Comment by Eonfge** [comment]
The new logo is bad because it's not resting on a background. This is a design feature of both Mac, Windows and Android style-guides, which can be found here:

- https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/
- https://developer.android.com/google-play/resources/icon-design-specifications
- https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos

The only noticeable exception is Linux, who by it's nature of free market competition has competing standards.

- GNOME: https://developer.gnome.org/hig/stable/icon-design.html.en
- Elementary OS: https://elementary.io/docs/human-interface-guidelines#iconography

_It's worth noting that GNOME doesn't care about backgrounds, but they do care about shapes, which is also nice to read about._

In the image posted by @olivier-manomano you can see how other applications follow the style guide on Mac. 

**What to do**

Two options if you ask me
- Revert the icon change
- Change the current icon and add a background

**Controversy?**

In another issue (https://github.com/VSCodium/vscodium/issues/472), the project leaders have stated that they don't want to make any changes which I think is dumb. This change is directly in conflict with multiple platform guides.

**Comment by thijsvandien** [comment]
Here's how the new icon looks for me...

![Screen Shot 2020-08-26 at 10 56 57](https://user-images.githubusercontent.com/2722238/91283477-f29b7980-e78a-11ea-8352-2b2fa39ca504.png)

**Comment by stripedpajamas** [comment]
Icon has been reverted (will be in next release). Meanwhile there's another vote to update the old icon to "Big Sur style" for Mac users in #591
