### ISSUE TITLE
Icon is too small in Linux

### ISSUE THREAD

**Issue by TomaszGasior** [VSCodium/vscodium#499]
VSCodium icon in last update has been changed to smaller (with bigger inner margin) and currently it's much smaller than icons of other apps.

My OS is Fedora 32 with default GNOME desktop.

App switcher:
![Zrzut ekranu z 2020-09-11 22-41-19](https://user-images.githubusercontent.com/1395027/92971096-1e537a80-f480-11ea-8dd4-0a148f5b6ac0.png)

Activities view:
![Zrzut ekranu z 2020-09-11 22-40-08](https://user-images.githubusercontent.com/1395027/92971179-3f1bd000-f480-11ea-89ac-12c6569476d9.png)

Panel (comparison with Firefox):
![Zrzut ekranu z 2020-09-11 22-40-21](https://user-images.githubusercontent.com/1395027/92971134-30351d80-f480-11ea-86e3-ea5d010dde0c.png)
![Zrzut ekranu z 2020-09-11 22-40-14](https://user-images.githubusercontent.com/1395027/92971159-36c39500-f480-11ea-82e0-e1d5060f5cf7.png)
BTW Here you can see it might be good idea to provide `-symbolic` icon too, for GNOME Shell top panel. Otherwise colorful icon is gray-scaled by GNOME Shell.

**Comment by CountZachula** [comment]
It shrunk in macOS too --- and now has a white background to compensate.

**Comment by benatkin** [comment]
It's too big in MacOS.
<img width="409" alt="Captura de Tela 2020-09-12 às 20 57 56" src="https://user-images.githubusercontent.com/4126/93007775-aeee9100-f53a-11ea-8560-8fae8ecf55d3.png">

**Comment by TomaszGasior** [comment]
Do you have current version of the app? My screenshots are from  1.49.0.

**Comment by benatkin** [comment]
1.48.2, says no updates available though

**Comment by stripedpajamas** [comment]
1.49.0 for Mac is busted currently, hence no update at the moment @benatkin

**Comment by jim4067** [comment]
Just discovered this. The icon is too small on the dock but normal on the launcher.

**Comment by cd4d** [comment]
See #491

**Comment by theArianit** [comment]
same in linux mint

**Comment by estatra** [comment]
Thanks for the report and feedback. People complained about the icon being too big, hence the change.

@CountZachula for macOS the icon follows the official macOS Big Sur icon guidelines for future proofing.
@benatkin Already fixed, but current macOS build is broken.

@TomaszGasior 
`BTW Here you can see it might be good idea to provide -symbolic icon too, for GNOME Shell top panel. Otherwise colorful icon is gray-scaled by GNOME Shell.`

It requires code and directory standards changes (not my area) and it might differ from upstream too much. If the code and standard is changed and I'm asked to update accordingly I'll be happy to help.

--

For Linux a similar approach was followed.

I suggest the community to choose a size of preference, since if either GNOME or KDE guidelines are followed, people complain that the icon is too big.

You can also vote on a standard, like GNOME or KDE, but then again there is a probability that people will complain again even if GNOME or KDE guidelines are followed.

Relevant links:
- https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/
- https://developer.gnome.org/hig/stable/icon-design.html.en
- https://community.kde.org/Guidelines_and_HOWTOs/Submit_an_icon

**Comment by TomaszGasior** [comment]
The problem seems to be fixed now.
