### ISSUE TITLE
CLI tool for vscodium

### ISSUE THREAD

**Issue by chris-vest** [VSCodium/vscodium#51]
Are there plans to include a CLI tool for vscodium?

**Comment by stripedpajamas** [comment]
@chris-vest what would the CLI do?

**Comment by lavaman** [comment]
I was about to make an issue about this same thing. I spend quite a bit of my time in a terminal and it would be nice to be able to open files in vscodium from the cli, like what MacVim does in it's brew cask by adding the mvim cli command.

**Comment by stripedpajamas** [comment]
That is already supported... in Visual Studio Code there is an option to add `code` to the PATH so that you can type `code [filename]` or `code [dir]` to open it up. VSCodium has the same thing. See https://github.com/VSCodium/vscodium/issues/18 and let me know if that's kind of what you're thinking of.

**Comment by lavaman** [comment]
Yeah, that's what I was thinking. Another documentation thing then :)

**Comment by stripedpajamas** [comment]
@lavaman 👍 

@chris-vest if this is what you were talking about as well I'll merge #53 and close this up

**Comment by chris-vest** [comment]
@stripedpajamas Exactly what I was after, thank you!
