### ISSUE TITLE
Error updating VSCODIUM if managed by package manager

### ISSUE THREAD

**Issue by kernie** [VSCodium/vscodium#512]
**Describe the bug**
VSCODIUM checks online whether there is an update available. It will install it after restarting the program. When VSCODIUM was installed by a package manager (apt, zypper, homebrew), the update will fail.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. Don't know.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install VSCODIUM by help of a package manager
2. Check for updates. 
3. Restart VSCODIUM

**Expected behavior**
If updates are managed by the package manager, automatic updates should be disabled in VSCODIUM

**Desktop (please complete the following information):**
 - OS: openSuSE 15.2, OSX 10.15.6
 - Architecture [AMD64]

**Comment by stripedpajamas** [comment]
>  If updates are managed by the package manager, automatic updates should be disabled in VSCODIUM

We don't have a way of detecting this, as far as I know.

I have not experienced update failures with OSX + Homebrew cask + auto updates through VSCodium. Can you provide more context there?

For Linux, I think it's safe to say that auto update is expected to fail, as the [update file simply points to a tar.gz file](https://github.com/VSCodium/versions/blob/master/linux/x64/latest.json). Open to suggestions for this scenario. We could just have no built-in auto updating for Linux since it is almost always handled by a package manager. Not sure how many people are using the tar.gz directly though.

**Comment by kernie** [comment]
I saw weird behavior (Icon in Dock was strange, vscodium window not responsive) when upgrading from 1.48 to 1.49 versions by automatic download and restart on OSX.

But I updated now from 1.49.1 to 1.49.2 and everything is fine.

Maybe we close this issue and I may reactivate it if I happen to get the problem again?

**Comment by stripedpajamas** [comment]
Ah yes, that is actually because the initial Mac 1.49 release was broken... more details about that and how it was resolved are in #498
