### ISSUE TITLE
Switching between marketplaces

### ISSUE THREAD

**Issue by pktiuk** [VSCodium/vscodium#519]
Hello,  
I am a user of vscodium since about two years, I really like this fork of vscode, but lately I have some issues with it.   
Most of them are caused by switching from proprietary store to [open-vsx](https://open-vsx.org/). I don't criticize this decision, but I want you to know how many troubles and annoyances it causes for regular users (I know using Microsoft's store can be problematic from legal point of view).

As a new user I would have no clue, why there is no access to some extensions. 
After looking for solutions in many issues and discussions among repository (it seems to be a time-consuming alternative for just downloading regular vscode) it appears that the simplest way of getting them is modification of file `product.json` https://github.com/VSCodium/vscodium/issues/418.  
It would be just one time inconvenience for loyal vscodium users, but it could be barrier for newcomers wanting to leave Microsoft's version.

This is problem for many users, the best measurement is number of issues describing it: https://github.com/VSCodium/vscodium/issues/514 https://github.com/VSCodium/vscodium/issues/508 https://github.com/VSCodium/vscodium/issues/493 https://github.com/VSCodium/vscodium/issues/483  https://github.com/VSCodium/vscodium/issues/463 etc...

Unluckily it appears that after every update (in my case I use PPA for regular Ubuntu package) Marketplace is broken and after every update I have to mess with `product.json` and this becomes a major inconvenience.

In this case I would like to suggest some (at least partial) solutions for this problem:
- Maybe it would be good to pin an issue/add note in README with instructions how to edit this file
- ensure preservation of applied changes in `product.json` between updates (seems to be not very invasive)
- add setting for using secondary marketplace (It seems to be invasive change into codebase, but it could be worth it in case of creation of another open-source marketplaces).

**Comment by articlecat** [comment]
The ["Code - OSS" Flatpak](https://github.com/flathub/com.visualstudio.code-oss) allows the user to override the default extensions gallery settings with a configuration file that is read at runtime.

https://github.com/flathub/com.visualstudio.code-oss/commit/f4fb6f33f410a59a04a5b564792e024b524fd2cc

This approach might also work for VSCodium.

**Comment by gukandrew** [comment]
Same here. We need that feature.
https://open-vsx.org is DEAD for me HTTP response 502.

**Comment by renestalder** [comment]
> ensure preservation of applied changes in product.json between updates (seems to be not very invasive)

That's the biggest issue for me here. While I can manually edit to use another marketplace, that change seems lost with every update.

**Comment by noonsleeper** [comment]
> The ["Code - OSS" Flatpak](https://github.com/flathub/com.visualstudio.code-oss) allows the user to override the default extensions gallery settings with an environment variable pointing to a configuration file that is read at runtime.
> 
> [flathub/com.visualstudio.code-oss@f4fb6f3](https://github.com/flathub/com.visualstudio.code-oss/commit/f4fb6f33f410a59a04a5b564792e024b524fd2cc)
> 
> This approach might also work for VSCodium.

Indeed this is [to me](https://github.com/flathub/com.vscodium.codium/issues/22) the correct approach but I don't see the license file anywhere in the repo and without it port this patch can be a problem, I'll ask to the developer of [com.visualstudio.code-oss](https://github.com/flathub/com.visualstudio.code-oss) for the license and if is ok to port his patch here then I'll make a merge request

**Comment by GitMensch** [comment]
Actually _not_ using the ms marketplace by default (and by any update) prevents you from:

* breaking the MS "store" license
* install extensions which license you also break by doing so
* install extensions that don't work because they explicit check for VS Code
* sending data to MS store via the API about used extensions, and check for those

I can only speak for myself, but I really _like_ that behavior. I won't tamper the product.json, but instead do what the main [README of this repo already talks about](https://github.com/VSCodium/vscodium#extensions-and-the-marketplace) and has a [DOCS entry](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) about:

>  * Ask the extension maintainers to publish to [open-vsx.org](https://open-vsx.org/) in addition to the VS Code Marketplace. The publishing process is documented in the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).
> * Create a pull request to [this repository](https://github.com/open-vsx/publish-extensions) to have the [@open-vsx](https://github.com/open-vsx) service account publish the extensions for you.

Keeping some (possibly broken) product.json with an update or re-install leads to "still broken" when you ... update or reinstall, I'd say this would also be not very ideal.

**Comment by pktiuk** [comment]
> Keeping some (possibly broken) product.json with an update or re-install leads to "still broken" when you ... update or reinstall, I'd say this would also be not very ideal.

I could say the same about continuous reversing changes in configs which I make to customize software for my needs.

**Comment by articlecat** [comment]
> Keeping some (possibly broken) product.json with an update or re-install leads to "still broken" when you ... update or reinstall, I'd say this would also be not very ideal.

This issue does not ask for the default marketplace to be switched back to the Visual Studio Marketplace. It asks for VSCodium to provide a more convenient way for users to select the Visual Studio Marketplace without having to change `/var/lib/flatpak/app/com.vscodium.codium/current/active/files/share/codium/resources/app/product.json` on every update.

If you are happy with Open VSX, this issue does not propose any changes that would affect you. This issue is for users who do not consider the licensing of the Visual Studio Marketplace configuration to be a problem, and would prefer to use Visual Studio Marketplace over Open VSX in VSCodium.

**Comment by jjasoncool** [comment]
hope this command help.
`sed -i 's/open-vsx.org\/vscode\/gallery/marketplace.visualstudio.com\/_apis\/public\/gallery/g; s/open-vsx.org\/vscode\/item/marketplace.visualstudio.com\/items/g;' /usr/share/codium/resources/app/product.json`

**Comment by noonsleeper** [comment]
This not only limited to "switch to the MS marketplace", Instead if any org try to setup a internal marketplace with a curated list of extensions for internal development using https://github.com/eclipse/openvsx as a server, actually they can't. Even more if you update vscodium package your changes are reverted to the original product.json, and from the flatpak version is more the same since is readonly. Actually my org have the first problem and I like see that vscodium have this feature for a better experience on as a user =).
As you see not all is black & white whit this type of changes

**Comment by GitMensch** [comment]
> As you see not all is black & white whit this type of changes

I'd say that's completely white :-) For this use-case it looks better to have an issue opened in the vscode repo as "Allow to override the marketplace URL and keep this setting after an update". I'd totally support that and from the 20 upvotes to this issue it looks like it would get the necessary 20 upvotes in the other repo to be kept.
As MS also allows for local update servers with the OS, I think it would be a reasonable comparison. And implementing it in the main vscode repo removes additional patching here and likely provides a better user-experience and testing, too.

What do you think?

**Comment by articlecat** [comment]
@GitMensch That's not a very practical suggestion. Microsoft has not yet responded to microsoft/vscode#31168, even though the issue was created over 3 years ago. If Microsoft wanted it to make it simple to access the Visual Studio Marketplace through the code in the [microsoft/vscode](https://github.com/Microsoft/vscode) repo, a Microsoft employee would have never used "Revert inadvertant change to product.json" as the commit message of [f1d0c1d88417f85ec66fa5629beca64ef71ac8b8](https://github.com/microsoft/vscode/commit/f1d0c1d88417f85ec66fa5629beca64ef71ac8b8).

Because vscode is open source, forks like VSCodium can give users more control over the software without having to ask Microsoft for permission. VSCodium already provides the option to change marketplaces, but implements the option in a way that burdens users with extra steps on every update. This issue simply suggests that VSCodium remove this burden.

If you do not want to use another marketplace, this issue does not affect you. Please don't insist on keeping this burden for other VSCodium users, when this issue does not do anything to impact your use of VSCodium.

**Comment by stripedpajamas** [comment]
VSCodium doesn't "provide the option to change marketplaces" any more than VSCode does. What "burden" can be removed here? PRs welcome.

**Comment by GitMensch** [comment]
> That's not a very practical suggestion.

Why not? MS doesn't ship their marketplace into the OSS code, that doesn't mean they'd have anything against providing a way to override whatever is in product.json. If you want to use this as an example: all MS OS ship with a "get all updates from MS servers" setting but when using a local update server this behavior changes - nothing more and nothing less.

I think it is more useful to use that analogy than to request MS that they make their marketplace officially accessible for any one which is mostly a legal issue. These are two very different things (even if providing the way to override product.json would _effectively_ making it more easy for people to access the vs-marketplace).

**Comment by renestalder** [comment]
@stripedpajamas 

> VSCodium doesn't "provide the option to change marketplaces" any more than VSCode does. What "burden" can be removed here?

I think the significant point is more that VSCodium is overwriting a part of VSCode in a way it (that's at least for me) breaks usability. To revert this part, I now run a script every time VSCodium was updated to revert the VSCodium overwrite of my setting. The "burden" I see VSCodium could lower is that my preference, which marketplace to use, isn't overwritten with every update.

**Comment by GitMensch** [comment]
The thing here is:

* an install **must** ship with a product.json, otherwise the vscode part would not work
* an _update_ should ideally update this single installed file (more specific only the entry for the marketplace) but override every other file

If you find any way to resolve this conflict a PR will be welcomed. But I _think_ the only way to resolve it is to come up with a new setting (additional file, environment variable, environment variable pointing to an additional file?) that takes precedence, which then should ideally be applied directly in the vscode repo.

**Comment by articlecat** [comment]
I've submitted pull request #537, which lets the user specify a custom extensions gallery through environment variables.

**Comment by GitMensch** [comment]
Thanks for the patch, that's very useful and can nearly also applied (or PR'd) to the vscode repo - I still suggest to do so, giving the corporate sample, if it is just "laying" there then VSCodium can use it via your patch (which would be one reason more to prefer VSCodium in business environments). And yes: it solves the marketplace issue, so if/as soon as #537 is merged the wiki page about that should be adjusted.

Thanks again (please consider s/VSCODIUM/VSCODE/g in that patch).

**Comment by renestalder** [comment]
@stripedpajamas Thanks for the detailed clarification. That helps a lot to understand the whole concept.

**Comment by pdfrod** [comment]
How much of a maintenance burden would it be to implement some logic to make VSCodium give priority to a user defined `product.json` (something like `$HOME/.config/VSCodium/product.json`) over the system `product.json`?

**Comment by bittner** [comment]
> Definitely the most viable option is not listed: make the marketplace a runtime variable, either by patching `vscode` at build time, or by patching upstream.

_Spoiler alert: I'm not a plugin author, so be warned, this question might be stupid!_

Would it be possible to come up with a plugin that can extend or override the values for or behavior of how to access the marketplace? If that were the case people should simply be able to install that plugin from the VSX marketplace.

An alternative approach would be to pimp up Code to support _additional_ marketplaces, similar to repository sources of modern Linux distros. Certainly, this approach would again be at the mercy of Mircosoft.

**Comment by NovaViper** [comment]
If it helps anyone, there's a [AUR (Archlinux User Repository)](https://aur.archlinux.org/packages/code-marketplace/) that adds the VSCode marketplace to VSCodium. I just installed it today and works perfectly :D

**Comment by GitMensch** [comment]
Thanks to @daiyam: With a current build of VSCodium (for most with the next release) you can have a partial product.json or use environment variables to override the default choice of open-vsx. See #674 for details.

**Comment by codrcodz** [comment]
If you're an arch user, you can install this package:

https://aur.archlinux.org/packages/vscodium-marketplace

If you're not an Arch user, you can download the files here:

https://aur.archlinux.org/cgit/aur.git/tree/?h=vscodium-marketplace

Then manually run the install commands at the bottom of the PKGBUILD file. You'll need to remove or replace the variables in those commands, and may also need to adjust the paths that it installs the files too, based on your OS. Alternately, you could start using an Arch-based distro. :-P
