### ISSUE TITLE
No x64 Linux release

### ISSUE THREAD

**Issue by turion** [VSCodium/vscodium#529]
I'm trying to package [vscodium for `nixpkgs`](https://github.com/NixOS/nixpkgs/pull/98088). This currently fails because the 1.50.0 release seems not to have produced an x64 artifact. I'm missing a file https://github.com/VSCodium/vscodium/releases/download/1.50.0/VSCodium-linux-x64-1.50.0.tar.gz.

Similar to https://github.com/VSCodium/vscodium/issues/500.

**Comment by popey** [comment]
I'm in a similar position building the codium snap. We ingest the deb, which is also missing.

**Comment by moritzheiber** [comment]
It's because [the Linux build process for the release failed](https://github.com/VSCodium/vscodium/runs/1228901384?check_suite_focus=true#step:8:3620), since it's missing `convert` from the `ImageMagick` toolkit for converting a PNG file, which is a part of the [AppImage build process](https://github.com/VSCodium/vscodium/blob/0355e7013c35884d85ee95dbdf13ce53ecda8947/VSCodium-AppImage-Recipe.yml#L26).

It'll likely be fixed by adding `imagemagick` as a dependency to the build step (which adds a `convert` [alternative](https://wiki.debian.org/DebianAlternatives) pointing to `/usr/bin/convert-im6.q16`, at least on Ubuntu Focal Fossa).

**Comment by stripedpajamas** [comment]
Opened #531 ; after I merge it, we should get the release. Apologies for the churn.

**Comment by stripedpajamas** [comment]
Releases are available.
