### ISSUE TITLE
VSCodium is more than twice the size of VSCode on MacOS

### ISSUE THREAD

**Issue by Jackymancs4** [VSCodium/vscodium#54]
Hello,
I have been following vscodium for a couple of months now, and decided to give it a try, but…
<img width="439" alt="schermata 2018-10-29 alle 23 14 48" src="https://user-images.githubusercontent.com/6209647/47683795-f7b03180-dbd0-11e8-81f9-d3dabaca6c00.png">
In the screen both of them were just downloaded from [vscodium](https://github.com/VSCodium/vscodium/releases/download/1.28.2/VSCode-darwin-1.28.2.zip) and [vscode](https://az764295.vo.msecnd.net/stable/7f3ce96ff4729c91352ae6def877e59c561f4850/VSCode-darwin-stable.zip).

I'm no expert of build pipelines, so I don't know if this is expected or not, but surely 430MB of size seems odd. Sorry if I get it wrong.

I also inspected both packages and inside VSCodium it appears to be three Electron.Framework bundles (by 70MB each), while in VSCode there is only one.

**Comment by stripedpajamas** [comment]
Wow good find @Jackymancs4. I wonder what we're doing wrong in the build process. I will investigate.

**Comment by stripedpajamas** [comment]
I used BeyondCompare to see the differences between the two packages. It looks like (as you pointed out @Jackymancs4) MS is somehow using links, whereas our build is producing duplicate folders (electron A vs electron current)

VSCode on left, VSCodium on right

![image](https://user-images.githubusercontent.com/2707340/47725199-81421c80-dc2e-11e8-8faa-1bb2c23b80fb.png)

**Comment by Jackymancs4** [comment]
Curiously, linux 32x & 64x builds of VSCode and VSCodium are comparable both in size and content.
So this is a problem only for darwin build target.

**Comment by stripedpajamas** [comment]
Alright I've figured it out. In Microsoft's build process, when they zip up the Darwin package ([here](https://github.com/Microsoft/vscode/blob/master/build/tfs/darwin/product-build-darwin.yml#L38)), they pass `-y` to the zip command.

From the zip man page:

-----
-y
--symlinks
For UNIX and VMS (V8.3 and later), store symbolic links as such in the zip archive, instead of compressing and storing the file referred to by the link. This can avoid multiple copies of files being included in the archive as zip recurses the directory trees and accesses files directly and by links.

-----

It ought to be that we can pass the same flag and get the small build. Trying that now on my own branch. File to change is [here](https://github.com/VSCodium/vscodium/blob/master/create_zip.sh#L6).

**Comment by JL2210** [comment]
VSCode has external dependencies. VSCodium doesn't.

**Comment by stripedpajamas** [comment]
@JL2210 what do you mean? This issue has already been resolved.

**Comment by JL2210** [comment]
Sorry. I just realized that. Maybe we could strip our binaries and remove unneeded stuff from the zips? Anyway, VSCode (no offense) is a lot more well done than VSCodium. They probably have all this stuff automated, for all I know.

**Comment by stripedpajamas** [comment]
@JL2210 you can look at their build process [here](https://github.com/Microsoft/vscode/blob/master/build/tfs/darwin/product-build-darwin.yml). They don't strip anything out, but they do add things (mixins). As of #55, our package size is _smaller_ than VSCode's.
