### ISSUE TITLE
Flatpak build writes config files outside of sandbox

### ISSUE THREAD

**Issue by BeatLink** [VSCodium/vscodium#547]
On flatpak builds, the app will create a folder in the homefolder called ~/.vscode-oss. The app should instead store these configuration files in its own .var folder

**Comment by x80486** [comment]
This is probably a hard-coded path in the source code rather than using the proper XDG locations. It also creates `${HOME}/.tooling/` sub-directory — not sure if it's the IDE or an extension because all I have in that one is a `gradle/` sub-sirectory, so it might be the RedHat Java extension.

Anyway, I don't think this is a Flatpak issue, because I've tested the AppImage and the (64-bits) ZIP and all behave in the same way.

**Comment by noonsleeper** [comment]
Hey @BeatLink there is a issue on codium's flatpak [repo](https://github.com/flathub/com.vscodium.codium/issues/31) for this problem

**Comment by BeatLink** [comment]
Thanks for keeping me posted! I'll subscribe to it

**Comment by daiyam** [comment]
It isn't limited to flatpak, VSCode has this behaviour on all the distros I've tested (#671).
