### ISSUE TITLE
Platformio IDE is not available as an extension 

### ISSUE THREAD

**Issue by DerHolli** [VSCodium/vscodium#637]
Hello everybody
yesterday I got the current release (1.53.0) in Ubuntu 20.04. I use snap to install. The Platformio IDE extension is not available in VSCodium. An attempt to install the extension directly via the platformio's vsix file also failed because the dependencies (C ++) do not exist or cannot be found. During my research I found that VSCodium does not access the Microsoft marketplace but has its own repository. I have not found a solution to my problem.

Thanks to the VSCodium team. Excellent work! 

best regards
Holger

**Comment by stripedpajamas** [comment]
Yes, I don't see PlatformIO on the extension marketplace that VSCodium uses (https://open-vsx.org).  Installing from vsix is one of the options specified [in our docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace); if that doesn't work due to some dependency issue, you might want to task the developers of the extension why that doesn't work (https://github.com/platformio/platformio-vscode-ide) -- and also perhaps that they should put their extension in Open VSX. Their repo seems to value "no vendor lock-in", so I expect they would be amenable to the idea.
