### ISSUE TITLE
Preserve Previous Product.json?

### ISSUE THREAD

**Issue by ralfbiedert** [VSCodium/vscodium#638]
**Describe the bug**

I just updated VS Codium and had a modified `product.json` (specifically the `extensionsGallery` section was set). Apparently the update replaced that with a new copy. 

- It would be nice if the old file could be preserved.
- Alternatively, the documentation should explain another way how to persist that setting between updates

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture arm64
 - Version 1.53.0 (system setup)

**Comment by stripedpajamas** [comment]
`product.json` is a build-time file, so it is replaced completely when a new version is installed. There is #537 which specifically addresses setting a sticky custom extensions gallery -- I think that would solve your issue. The PR has gone a bit stale, but I think the idea is still good. Since #537 references #519, I will close this as a duplicate.

(If you really want sticky `product.json`, and not just the extension gallery setting, the issue belongs in vscode's repo).
