### ISSUE TITLE
flatpak package

### ISSUE THREAD

**Issue by fafa2017** [VSCodium/vscodium#65]
Is it possible to have vscodium as flatpak package in the near future?
thank,

`

**Comment by stripedpajamas** [comment]
Hi @fafa2017 👋 

There aren't any current plans to support flatpak in this project, but if anyone has time/knowledge to implement it, the PR would be very welcome. I know it's tricky since it means building `vscode` without internet and that gets complicated. 

You might already know about this -- there exists a flatpak for Visual Studio Code - OSS (which is the same as VSCodium except that in this project we jump through a couple of hoops to remove Microsoft's telemetry). That link is here: https://flathub.org/apps/details/com.visualstudio.code.oss and the repo is here: https://github.com/flathub/com.visualstudio.code.oss. It is not supported or officially recommended by VSCodium but if a flatpak of the MIT licensed build of Microsoft's `vscode` repo is what you need, there it is.

**Comment by fafa2017** [comment]
Hi @stripedpajamas 
I would like to try a vscodium ,and I downloaded the "VSCode-linux-x64-1.29.1.tar.gz" and when I run it on from a terminal I get this message :
> ./vscodium: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory"

**Comment by stripedpajamas** [comment]
Hmmm. 

Can you let me know your OS and arch? 

Also would you be able to try the Microsoft version https://go.microsoft.com/fwlink/?LinkID=620884 and see if you have the same issue? I'm wanting to see if this is a problem with how we build or if this is something bigger.

Thanks @fafa2017

**Comment by fafa2017** [comment]
I have resolved the problem by installing the libXScrnSaver package.
Thank you for this intervention

**Comment by Eonfge** [comment]
@fafa2017 Bit late, but this is what you want:
https://flathub.org/apps/details/com.visualstudio.code.oss
