### ISSUE TITLE
Codium freezing since upgrade

### ISSUE THREAD

**Issue by sparusaurata** [VSCodium/vscodium#667]
**EDIT :** My first diagnosis was wrong, see [this comment](#issuecomment-801308779).

Since I upgraded to 1.53, when I start Codium the extensions seem not to be loaded.
Concretely I use Codium with `prettify-symbols-mode` and `vscoq` and none of them does work.
When rolling back to 1.52 the problem disappears. I use a Linux Mint 18.3 system.

(Excuse my poor English...)

**Comment by absozero** [comment]
Same here, wierdly didn't work for me on 1.52 either.

**Comment by daiyam** [comment]
When loading `vscoq` on 1.53, I didn't have any errors. Did you get an error?

**Comment by absozero** [comment]
To be honest, I got an error with Live Share made by ms-vsliveshare. I need it as I am doing a project with a friend using this extension and I was not able to sign in and use this extension to share. This was troubling to me, since I did not want to use VS code given by Microsoft since I was sure there would be a lot of tracking in it, and the license wasn't friendly. The Live Share extension worked with Codium before, but hasn't worked on the latest release. Could somebody help?

**Comment by sparusaurata** [comment]
I updgraded to 1.54, now it's even worse: Codium freezes when I launch it (the only tab opened is a Coq file).
There are two `codium` processes, each one uses use all the resources of a processor core and I have to kill them both to close the program.

**Comment by daiyam** [comment]
@sparusaurata Hum... How you have installed the extension? By changing the `product.json` or with `vsix` files?

**Comment by sparusaurata** [comment]
Okay, in fact the extensions were not the problem: I removed Codium (and manually deleted all residual config files, including the extensions), and re-installed it. And now my fresh Codium install freezes exactly in the same way...

**Comment by daiyam** [comment]
On Linux Mint 18.3, for me, the 1.53 is working but 1.54 doesn't. VSCode 1.54 is working fine.

**Comment by sparusaurata** [comment]
I eventually solved the problem in an efficient but not-so-satsifying way: I installed Mint 20.1 and re-installed Codium from scratch...
