### ISSUE TITLE
code binary not working from command line in version 1.15.5 when installed with homebrew

### ISSUE THREAD

**Issue by mTvare6** [VSCodium/vscodium#696]
**Describe the bug**
Unable to launch from CLI when installed with brew in 1.15.5

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install latest version using brew package manager
2. run `code .` like older versions

**Expected behavior**
VSCodium lauch from the directory as every other version

**Actual behavior**
No binary found in that name

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Architecture x64
 - Version  11.3

**Additional context**
Latest version 1.15.5

**Comment by daiyam** [comment]
The binary's name was `code` only on macOS and it was causing conflict with Visual Studio Code's binary (also named `code`).
Since 1.55, it was fixed so that, on all platforms, the binary's name is `codium`.
If you don't like that you can add the alias `alias code='codium'` in the file `~/.bash_login`

**Comment by mTvare6** [comment]
Aliasing doesn't work in certain cases so `ln -s /usr/local/bin/codium /usr/local/bin/code` I linked them
