### ISSUE TITLE
Cooperate with com.visualstudio.code.oss from flathub

### ISSUE THREAD

**Issue by G-Ray** [VSCodium/vscodium#7]
@amtlib-dot-dll is doing a great job packaging the open source version of vscode to flathub.org (https://flathub.org/apps/details/com.visualstudio.code.oss).

Maybe vscodium contributors can merge efforts with him to avoid confusion between various OSS versions.

I propose to:
- Use the same project name. We could rename vscodium to `CodeOSS`, the contrary or pick another neat name.
- Merge doc and code if necessary, under the same repo, and indicate that a flatpak build is available on flathub.org.
- Create a static site to showcase the product and link to installation packages

**Comment by amtlib-dot-dll** [comment]
@G-Ray Thank you

@stripedpajamas Awesome for your project

* "Code - OSS" is the name used in the [upstream](https://github.com/Microsoft/vscode/blob/master/product.json#L2), and I don't know why Microsoft put this name rather than "Visual Studio Code" in the publically available repository. Naming is unimportant
* IMHO, codes here are far less than [my recipe to build the Flatpak package](https://github.com/flathub/com.visualstudio.code.oss/blob/master/build.py) because Flathub requires offline builds. It's awesome for you to add a link mentioning that there is a Flatpak build of the open source version of Visual Studio Code
* We don't need Wine or something else to build the Windows package. There is a free service called [AppVeyor](https://www.appveyor.com/) and it is what Microsoft use to test the Windows build of Visual Studio Code some time ago
* I noticed that `NODE_ENV=production` is used in [the build script](https://github.com/VSCodium/vscodium/blob/master/build.sh#L9). Long time ago when I tried to build it, this environment variable disrupts the build. Perhaps someone fixed it
* [This line](https://github.com/VSCodium/vscodium/blob/master/build.sh#L7) should be a secret for Microsoft but they leaked it by accident so you will see it everywhere. I prefer scraping it from [here](https://github.com/Microsoft/vscode/blob/b00945fc8c79f6db74b280ef53eba060ed9a1388/product.json)
* Welcome for discussion if you have any more questions

**Comment by rugk** [comment]
> I will link to the Flatpak package in the README for anyone who wants that.

It's still not linked or did I miss something? @stripedpajamas

**Comment by stripedpajamas** [comment]
@rugk sorry! Forgot to update the README. I'll reopen this until a PR is merged that closes it
