### ISSUE TITLE
How to debug/run C++ in vscodium?

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#750]
Does `ms-vscode.cpptools` have to be installed?

**Comment by Casper24162** [comment]
Yes. For things like IntelliSense you need the C/C++ extension. If you want to run your code quickly, you can download the extension Code Runner _(see command below)_ to run your code quickly instead of using a batch/shell script or the terminal to compile and execute. Debugging tools are included in the C/C++ extension.

**Install code runner:**
Open Codium, press Ctrl+P paste this command:
`ext install formulahendry.code-runner`
