### ISSUE TITLE
How to compile for debian i386 platform?

### ISSUE THREAD

**Issue by vbuterin2** [VSCodium/vscodium#751]
I do not want to upgrade to amd64, but want to compile it on my own

**Comment by daiyam** [comment]
The lastest version supported on Linux 32bit is the `1.35`. Here why: https://code.visualstudio.com/updates/v1_36#_linux-32bit-support-ends

**Comment by stripedpajamas** [comment]
There are docs for how to compile on your own here https://github.com/VSCodium/vscodium/blob/master/docs/build.md (they might not work exactly because as @daiyam mentioned, 32bit builds are unsupported since v1.35). 

MS also has self-compile documentation here: https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites

We tried to automate their instructions with CI build scripts, applying some patches here and there along the way.
